<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $crumbs = $this->getBreadcrumb()?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <div class="category-list-sidebar">
        <ul class="paddingl0">
            <li><strong><?php echo __('Product categories') ?></strong></li>

            <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>

            <?php
                $label = $block->escapeHtml($crumbInfo['label']);
                $link = $block->escapeUrl($crumbInfo['link']);
            ?>
            <li class=" <?php /* @escapeNotVerified */ echo $block->escapeHtml($crumbName) ?>">
            <?php if ($link) : ?>
                    <a href="<?php /* @escapeNotVerified */ echo $link ?>"
                       title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                    <?= $label ?>
                    </a>
                    <?php elseif ($crumbInfo['last']) : ?>
                    <strong><?= $label ?></strong>
                <?php else: ?>
                    <?= $label ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
