<?php
/**
 * Copyright © 2015 PlazaThemes.com. All rights reserved.

 * @author PlazaThemes Team <contact@plazathemes.com>
 */
?>
<?php
/**
 * Blog post info template
 *
 * @var $block \Plazathemes\Blog\Block\Post\Info
 */
?>

<?php $_post = $block->getPost() ?>

<div class="post-info clear">
    <div class="item post-posed-date"> 
        <span class="day"><?php echo $block->getPostedOn('d') ?></span>
		<span class="month"><?php echo $block->getPostedOn('M') ?></span>
    </div>
    <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
    <div class="dash">|</div>
    <div class="item post-categories">
        <span class="label"><?php echo __('Categories:') ?></span>
        <?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
            <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
            <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
        <?php } ?>
    </div>
    <?php } ?>
</div>