<?php $block->renderFileLessToCss(); ?>
<header class="header-container" >
	
		<div class="header-wrapper">
		<div class="header">
			<div class="container-inner">
				<div class="header-inner">
					<div class="logo-wrap">
						<div class="nav-ozmegamenu-inner">
				<div class="mobile-bar-icon"><span><?php /* @escapeNotVerified */ echo __('mobile icon'); ?></span></div>
			</div>
			<div class="mobile-bar-content">
				<div class="Cflag-wrap">	
									<span class="Cflag"><img src="<?php echo $block->getViewFileUrl('Wcb_Megamenu::images/flag.png'); ?>" /></span>
									<span><?php echo __("Croatia"); ?></span>

								</div>	
				<div class ="mobile-bar-close"><?php /* @escapeNotVerified */ echo __('Close'); ?></div>
				<ul class = "tabs-mobile">
					<!--<li class="item item-menu"><?php /* @escapeNotVerified */ echo __('Menu-1'); ?></li>-->
				</ul>
				<div class="tabs-content-mobile tabs-menu">
					<?php echo $this->getChildHtml("mobilemenus");  ?>				
				 </div>
			</div>
						<?php echo $this->getChildHtml("logo"); ?>
					</div>
					
					<div class="minicart-wrap">
						<div class="absolute">
							
							<div class="link-hover" data-bind="scope: 'customer'" >
								<p class="icon"></p> <span class="accountTitle"><!-- ko if: customer().firstname  --> <span data-bind="text: new String('Moj Wurth')"></span> <!-- /ko -->  <!-- ko ifnot: customer().firstname  --> <a href="<?php echo $block->getUrl("customer/account/login"); ?>"> <span data-bind="text: new String('Login / Registration')"></span></a> <!-- /ko -->  </span>
		                    <!-- ko if: customer().firstname  -->
								<div class="account-wraper"> 
								 
									<div class="my-acount">	
										<div class="label welcome"> 
											<strong>
												<span class="logged-in" data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1', '%1')) ?>').replace('%1', customer().firstname)">
												</span> 
											</strong>
										</div>									
									<div class="label"> <span><a href="<?php echo $block->getUrl("customer/account"); ?>"><span data-bind="text: new String('My acoount')"></span></a></span></div>
									<div class="label"><span><a href="<?php echo $block->getUrl('customer/account/logout'); ?>"> <span data-bind="text: new String('Sign out')"></span></a></span></div>										
									</div>							
									
								</div>
								 <!-- /ko -->
							</div>
							<?php echo $this->getChildHtml("minicart");?>
						</div>
					</div>

						<div class="search-wrap">
						
						<?php echo $this->getChildHtml("top.search"); ?>	
					</div>

			</div>
			</div>
		</div>

		<div class="nav-menu">
			<div class="container-inner">
				<?php echo $this->getChildHtml("wcbmegamenu_top"); ?>
			</div>
		</div>	
		</div>	
</header>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>



