<div class="promotion-banners container-inner">
	<div class="row" id="ajaxresponse"></div>
</div>
<?php
$currentProductId = 1;
$ajaxurl = $block->getAjaxUrl();
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Wcb_PromotionBanner/js/custom": {
                    "AjaxUrl": "<?php echo $ajaxurl; ?>",
                    "CurrentProduct": "<?php echo $currentProductId; ?>"
                }
            }
        }
</script>