<?php
$category = $block->getEnableCategory();
?>

      <div class="column left-breadcrumbs">
         <div class="category-list-sidebar cat-arrow">        
            <ul class="paddingl0">  
            <li><?php echo __("Product Categories")?></li>
            <?php foreach ($category as $categorydata) : ?>
    <?php
    $categoryid = $categorydata->getEntityId();
    $categoryFactory = $block->getCategoryName($categoryid);
    $categoryName = $categoryFactory->getName();
    $categoryUrl = $categoryFactory->getUrl();
    $productCount = $categoryFactory->getProductCount();
    if($productCount > 0){
    ?>             
               <li class="category">
               <a class="category-link-show" href="<?php echo $categoryUrl; ?>" alt="<?php echo $categoryName; ?>"
           title="<?php echo $categoryName; ?>"><span> <img src="/media/catalog/category/p4_1.png" class="sidebar-cat-image">  </span><?php echo $categoryName; ?>
        </a>
               </li>
               <?php }endforeach; ?>
              
            </ul>
         </div>
      </div>
  