<?php
$category = $block->getEnableCategory();
?>

      <div class="column left-breadcrumbs">
         <div class="category-list-sidebar cat-arrow">        
            <ul class="paddingl0">  
            <li><?php echo __("Product Categories")?></li>
            <?php foreach ($category as $categorydata) : ?>
    <?php
    $categoryid = $categorydata->getEntityId();
    $categoryFactory = $block->getCategoryName($categoryid);
    $categoryName = $categoryFactory->getName();
    $categoryUrl = $categoryFactory->getUrl();
    $activeCount = $categorydata->getChildrenCategories()->addIsActiveFilter()->count();
    $activeSize = $categorydata->getChildrenCategories()->addIsActiveFilter()->getSize();
    $productCount = $categorydata->getProductCollection()->addAttributeToSelect('*')->count();
    if($activeCount > 0 && $activeSize > 0 && $productCount > 0){
    ?>             
               <li class="category">
               <a class="category-link-show" href="<?php echo $categoryUrl; ?>" alt="<?php echo $categoryName; ?>"
           title="<?php echo $categoryName; ?>"><span class="sidebarCatImg"> <img src="<?php echo $this->getViewFileUrl('Wcb_Catalog::images/alati.png'); ?>" class="sidebar-cat-image">  </span><span class="sidebarCatName"><?php echo $categoryName; ?></span>

        </a>
               </li>
               <?php }endforeach; ?>
              
            </ul>
         </div>
      </div>
  