<?php
$category = $block->getEnableCategory();
?>
<h2 align="center"><?php echo __("Product Categories")?></h2>
<?php foreach ($category as $categorydata) : ?>
    <?php
    $categoryid = $categorydata->getEntityId();
    $categoryFactory = $block->getCategoryName($categoryid);
    $categoryName = $categoryFactory->getName();
    $categoryUrl = $categoryFactory->getUrl();
    $productCount = $categoryFactory->getProductCount();
    if($productCount > 0){
    ?>
    <div>
        <a class="category-link-show" href="<?php echo $categoryUrl; ?>" alt="<?php echo $categoryName; ?>"
           title="<?php echo $categoryName; ?>"><?php echo $categoryName; ?>
        </a>
    </div>
<?php }endforeach; ?>