<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Amasty_Base
*/
?>
<?php
/** @var \Amasty\Base\Block\Adminhtml\System\Config\InformationBlocks\ExistingConflicts $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php $messages = $block->getConflictsMessages(); ?>
<?php if (!empty($messages)): ?>
    <div class="amasty-conflicts-title">
        <?= $escaper->escapeHtml(__('Problems detected:')) ?>
    </div>
    <div class="amasty-disable-extensions">
        <?php foreach ($messages as $message): ?>
            <p class="message message-error"><?= $escaper->escapeHtml($message) ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
