<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php //echo $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>
<?php $sku = $block->getProduct()->getSku();?>
<?php $productCode = $block->getProduct()->getProductCode();?>
<!-- Please use blubox, bluevan, redbox, redvan class to change box color-->
<?php
  // login check helper
   $logedIn=$this->helper("Wcb\Component\Helper\Data")->isLoggedIn();
 ?>
<?php if($logedIn) { ?>
<div class="itemboxwrapp"><span id="stockStatusP" ></span><span id="deliverydayVan" style="display:none;" ></span><span id="deliverydayP" style="display:none;" class="deliveryday"></span> <span class="itembox"> </span> <span class="deliveryday"></span><span> <?php echo floatval($this->getPackageBox($sku));?></span> </div>
<?php } ?>
<span class="hrline"></span>

<script>
require(['pdp'], function(pdp) {
               pdp.soapStock("<?php echo $productCode ?>");
            });
</script>
