<?php $collection = $block->getImportQtyData(); ?>

<?php foreach ($collection as $item) { ?>
    <div class="purchaseWrapp">
        <span class="proqty">Purchase this product in <?php echo $item->getQuantity(); ?> quantity</span>
        <span class="dodajwrap">
            <button data-qty="<?php echo $item->getQuantity(); ?>"
                    id='cusatc'
                    type="button"
                    class="dodaj multi-qty-add" >
                Dodaj u kosaricu
            </button>
        </span>
    </div>
<?php } ?>
<?php if ($collection->count() > 0) { ?>
    <span class="hrline"></span>
<?php } ?>
<script>
    require(['jquery'],function($){
        $('.multi-qty-add').click(function(){
            let productId =  '<?php echo $block->getProduct()->getId(); ?>';
            let qty = $(this).attr("data-qty");
            let data = {product: productId, qty: qty};
            let addToCartUrl = "<?php echo $block->getUrl('qtyimport/product/addToCart') ?>";
            $.ajax({
                url : addToCartUrl,
                dataType : 'json',
                type : 'POST',
                showLoader: true,
                data: data,
                success : function(res)
                {
                }
            });
        })
    })
</script>
