<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="wishlistwrap">
    <div class="pdrepbug"><button type="submit" class="itembug"><span class="icon-web-warning"></span> Report a bug</button></div>
    <div class="itemwish">
        <button class="itemwishbut">
            <a href="#"
               data-post='<?php echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($block->getProduct()) ?>'
               data-action="add-to-wishlist">
                <span class="icon-interface-heart">
                </span> Add to wishlish
            </a>
        </button>
    </div>
</div>
