<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php //echo $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    $logedIn = $customerSession->isLoggedIn();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$product_id = $product->getId();
$test = $objectManager->create(\Wcb\QuantityImport\Model\QuantityImport::class);
$collection= $test->getCollection()->addFieldToFilter('product_code', array('eq'=>$product->getProductCode()));
?>

<div class="static-content">

<div class="pdAku">AKU BUSILICA ODVIJAC-ABS 12 COMPACT-2X2,O AH</div>
<div class="brArt">br.art. 701 101002</div>
<span class="hrline"></span>
<div class="priceDisplay"><?php if($customerSession->isLoggedIn()) { ?>Price :   2,421.56 - 25% = 1,816.17 HRK/COM <span class="redStar"></span> <?php } else { ?> Price display for customers after registration <?php } ?></div>

<div class="boxcontaner">
      <div class="qty-field">
        <div id="79-dec" class="decreaseQty icon-interface-minus"></div>
        <input id="cart-79-qty" name="cart[79][qty]" data-cart-item-id="Test product" value="1" type="number" size="4" step="any" title="Qty" class="input-text qty" data-validate="{required:true,'validate-greater-than-zero':true}" data-role="cart-item-qty">
        <div id="79-upt" class="increaseQty icon-interface-plus"></div>
      </div>
      <div class="veCount">
      Packaging 100
      </div>  
        <div class="pdvariants">
          <button type="submit" class="itemAdd">Dodaj u kosaricu</button>
        </div>     
</div>
<?php if($customerSession->isLoggedIn()) { ?><div class="itemboxwrapp"><span class="redbox"></span><span class="redvan"></span><span class="deliveryday">10-14</span> <span class="itembox"> </span> <span class="deliveryday"></span><span> 1</span></div><?php } ?>

<span class="hrline"></span>
<?php foreach ($collection as $item) {?>
          
<div class="purchaseWrapp">
    <span class="proqty">Purchase this product in <?php echo $item->getData('quantity');?> quantity</span> 
    <span class="dodajwrap"><button  mydata="<?php echo $item->getData('quantity');?>" id='cusatc-<?php echo $item->getData('quantity');?> ' type="submit" class="dodaj">Dodaj u kosaricu</button></span>
</div>
<?php } ?>
<span class="hrline"></span>
<div class="col-md more-info-block">
<h3>Need More Information?</h3>
 <span class="phoneEmail">Contact us by phone or email?</span>
 <div><span class="icon-com-phone-a"></span> <span class="iphone-outline">Phone 0800 4260</span></div>
 <div><span class="icon-wuerth-e-mail"></span><span class="email-outline">Email wuert@wuerth.com.hr</span></div>
</div>

<div class="wishlistwrap">
    <div class="pdrepbug"><button type="submit" class="itembug"><span class="icon-web-warning"></span> Report a bug</button></div>
    <div class="itemwish"><button type="submit" class="itemwishbut"><span class="icon-interface-heart"></span> Add to wishlish</button></div>
</div>
    <div class="col-md-6 social-block">
    <ul>
<li><a href="#!" role="button"><span class="icon-whatsapp"></span></a></li>
<li><a href="#!" role="button"><span class="icon-call"></span></a></li>
<li><a href="#!" role="button"><span class="icon-linkdin"></span></a></li>
<li><a href="#!" role="button"><span class="icon-facebook"></span></a></li>
<li><a href="#!" role="button"><span class="icon-youtube"></span></a></li>
</ul>
</div>
</div>

<script type="text/javascript">
require(['jquery'], function($) {
    $(document).ready(function() {  
var incrementPlus;
var incrementMinus;
var buttonPlus  = $(".increaseQty");
var buttonMinus = $(".decreaseQty");
var incrementPlus = buttonPlus.click(function() {
	var $n = $(".qty")
	$n.val(Number($n.val())+1 );
});

var incrementMinus = buttonMinus.click(function() {
		var $n = $(".qty")
	var amount = Number($n.val());
	if (amount > 1) {
		$n.val(amount-1);
	}
});

});
});
  </script>

<script>
    require(['jquery'],function($){
        $('#cusatc').click(function(){
            var productId =  '<?php echo $product_id; ?>';
            var qty = $(this).attr("mydata");
            var data = {product: productId, qty: qty};
            var addToCartUrl = "<?php echo $block->getUrl('qtyimport/product/addToCart') ?>";
            $.ajax({
                url : addToCartUrl,
                dataType : 'json',
                type : 'POST',
                showLoader: true,
                data: data,
                success : function(res)
                {   
                    console.log('Success');
                },
                error : function()
                {
                    console.log('error');
                }
            });
        })
    })
</script>