<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php //echo $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>

<div class="static-content">

<div class="pdAku">AKU BUSILICA ODVIJAC-ABS 12 COMPACT-2X2,O AH</div>
<span class="hrline"></span>
<div class="pdversion">Available in 2 version</div>
<div class="pdvariants"><button type="submit" class="itemAdd">Show variants</button></div>
<span class="hrline"></span>
<div class="col-md-6 more-info-block">
<div class="moreInfo">Need More Information?</div>
 <span class="phoneEmail">Contact us by phone or email?</span>
 <div><span class="icon-com-phone-a"></span> <span class="iphone-outline">Phone 0800 4260</span></div>
 <div><span class="icon-wuerth-e-mail"></span><span class="email-outline">Email wuert@wuerth.com.hr</span></div>
</div>

    <div class="pdrepbug"><button type="submit" class="itembug"><span class="icon-web-warning"></span> Report a bug</button></div>
    <div class="col-md-6 social-block">
    <ul>
<li><a href="#!" role="button"><span class="icon-whatsapp"></span></a></li>
<li><a href="#!" role="button"><span class="icon-call"></span></a></li>
<li><a href="#!" role="button"><span class="icon-linkdin"></span></a></li>
<li><a href="#!" role="button"><span class="icon-facebook"></span></a></li>
<li><a href="#!" role="button"><span class="icon-youtube"></span></a></li>
</ul>
</div>

</div>

