<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php //echo $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>

<div class="col-md-6 social-block">
    <ul>
        <li><a href="#!" role="button"><span class="icon-whatsapp"></span></a></li>
        <li><a href="#!" role="button"><span class="icon-call"></span></a></li>
        <li><a href="#!" role="button"><span class="icon-linkdin"></span></a></li>
        <li><a href="#!" role="button"><span class="icon-facebook"></span></a></li>
        <li><a href="#!" role="button"><span class="icon-youtube"></span></a></li>
    </ul>
</div>