<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php //echo $block->getReviewsSummaryHtml($block->getProduct(), false, true) ?>
<!-- Please use blubox, bluevan, redbox, redvan class to change box color-->
<div class="itemboxwrapp"><span class="bluebox"></span><span class="bluevan"></span><span class="deliveryday">10-14</span> <span class="itembox"> </span> <span class="deliveryday"></span><span> 1</span> </div>
<span class="hrline"></span>
