<?php /** @var $block \Magento\Downloadable\Block\Catalog\Product\Links */ ?>

<?php $_linksPurchasedSeparately = $block->getLinksPurchasedSeparately(); ?>
<?php if ($block->getProduct()->isSaleable() && $block->hasLinks()): ?>
    <?php $_links = $block->getLinks(); ?>
    <?php $_linksLength = 0; ?>
    <?php $_isRequired = $block->getLinkSelectionRequired(); ?>
    <legend class="legend links-title">
        <?= $block->escapeHtml($block->getLinksTitle()) ?>
    </legend>
    <br>
    <div class="field downloads<?php if ($_isRequired) {
        echo ' required';
                               } ?><?php if (!$_linksPurchasedSeparately) {
        echo ' downloads-no-separately';
                               } ?>">
        <label class="label">
            <?=  $block->escapeHtml($block->getLinksTitle()) ?>
        </label>
        <div class="control" id="downloadable-links-list"
             data-container-for="downloadable-links">
            <?php foreach ($_links as $_link): ?>
                <?php $_linksLength++;?>
                <div class="field choice" data-role="link">
                    <?php if ($_linksPurchasedSeparately): ?>
                        <input type="checkbox"
                            <?php if ($_isRequired): ?>
                                data-validate="{'validate-one-checkbox-required-by-name':'downloadable-links-list'}"
                            <?php endif; ?>
                               name="links[]"
                               id="links_<?= $block->escapeHtml($_link->getId()) ?>"
                               value="<?= $block->escapeHtml($_link->getId()) ?>"
                                      <?= $block->escapeHtml($block->getLinkCheckedValue($_link)) ?> />
                    <?php endif; ?>
                    <label class="label" for="links_<?= $block->escapeHtml($_link->getId()) ?>">
                        <?= $block->escapeHtml($_link->getTitle()) ?>
                        <?php if ($_link->getSampleFile() || $_link->getSampleUrl()): ?>
                            <a class="sample link"
                               title="<?=  $block->escapeHtml(__('sample')) ?>"
                               href="<?= $block->escapeUrl($block->getLinkSampleUrl($_link)) ?>"
                                <?= $block->getIsOpenInNewWindow() ? 'target="_blank"' : '' ?>>
                                <?=  $block->escapeHtml(__('sample')) ?>
                            </a>
                        <?php endif; ?>
                    </label>
                </div>
            <?php endforeach; ?>
            <?php if ($_linksPurchasedSeparately && $_linksLength > 1): ?>
                <div class="field choice downloads-all">
                    <input type="checkbox"
                           data-notchecked="<?= $block->escapeHtml(__('Select all')) ?>"
                           data-checked="<?= $block->escapeHtml(__('Unselect all')) ?>"
                           id="links_all" />
                    <label class="label" for="links_all">
                        <?= $block->escapeHtml(__('Select all')) ?>
                    </label>
                </div>
            <?php endif; ?>
        </div>
        <?php if ($_isRequired): ?>
            <span id="links-advice-container"></span>
        <?php endif;?>
    </div>
    <script>
        require(
            [
                'jquery',
                'Magento_Downloadable/downloadable'
            ], function($) {
                $('[data-role=ampromo-overlay]').on('init.ampopup', function () {
                    initDownloadable();
                });

                function initDownloadable() {
                    $('#ampromo_items_form-<?= (int)$block->getProduct()->getId() ?>').downloadable({
                        linkElement: 'input:checkbox[value]',
                        allElements: '#links_all',
                        priceHolderSelector: '.price-box-<?= (int)$block->getProduct()->getId() ?>',
                        config: <?= /* @noEscape */$block->getJsonConfig() ?>
                    });
                }
            });
    </script>
<?php endif; ?>
