<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
<td class="cols sku" data-th="<?= $block->escapeHtml(__('RB')) ?>">1</td>
    <td class="cols sku" data-th="<?= $block->escapeHtml(__('Status')) ?>"><span class="red-box"></span></td>
    <td class="cols sku" data-th="<?= $block->escapeHtml(__('Br. art')) ?>">K8921050A</td>
    <td class="cols sku" data-th="<?= $block->escapeHtml(__('Ordered quantity')) ?>">12</td>
    <td class="cols sku" data-th="<?= $block->escapeHtml(__('Pack')) ?>">12</td>
    <td class="cols sku" data-th="<?= $block->escapeHtml(__('Delivered quantity')) ?>">12</td>
    <td class="cols name" data-th="<?= $block->escapeHtml(__('Name')) ?>">
        <?= $block->escapeHtml($_item->getName()) ?>
        <?php if ($_options = $block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($_options as $_option): ?>
                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                <?php if (!$block->getPrintStatus()): ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                    <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                        <?= $block->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                            <div class="tooltip content">
                                <dl class="item options">
                                    <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                    <dd><?= $block->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                                </dl>
                            </div>
                        <?php endif; ?>
                    </dd>
                <?php else: ?>
                    <?php $optionValue = isset($_option['print_value']) ? $_option['print_value'] : $_option['value'] ?>
                    <dd><?= $block->escapeHtml($optionValue) ?></dd>
                <?php endif; ?>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock): ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
   
    <td class="cols sku" data-th="<?= $block->escapeHtml(__('Delivery note number')) ?>">--</td>
    <td class="cols sku" data-th="<?= $block->escapeHtml(__('Date of dispatch')) ?>">08/27/2020</td>
    <td class="cols sku" data-th="<?= $block->escapeHtml(__('Invoice number')) ?>"> </td>
    <td class="cols sku" data-th="<?= $block->escapeHtml(__('Invoice date')) ?>">08/27/2020</td>
    <td class="cols sku" data-th="<?= $block->escapeHtml(__('Planned delivery date')) ?>">--</td>
    
</tr>
