<?php $collection = $block->getBlogCollection();?>
<?php if($collection->count() > 0): ?>  
    <?php
     function limitTextChars($content = false, $limit = false, $stripTags = false, $ellipsis = false) 
     {
         if ($content && $limit) {
             $content  = ($stripTags ? strip_tags($content) : $content);
             $ellipsis = ($ellipsis ? "..." : $ellipsis);
             $content  = mb_strimwidth($content, 0, $limit, $ellipsis);
         }
         return $content;
     }
    ?>  
    <section class="cmsHomeInfoCard container-inner">
    <div class="row">
    <?php foreach ($collection as $key => $data): ?>    
       <div class="col-md-3 col-sm-6">
            <div class="infoCard">
                    <img src="<?php echo $this->getMediaFolder().'/'. $data->getImage(); ?>" class="img-fluid">               
                        <h3><?php echo limitTextChars($data->getTitle(), 44, true, true); ?></h3>
                        <p class="des"><?php echo limitTextChars($data->getContent(), 145, true, true); ?></p>
            </div>
        </div>
        <?php endforeach; ?>  
        <?php else: ?>
    <h2>We couldn't find any records</h2>
<?php endif; ?>
</div>
</section>

