<?php $collection = $block->getBlogCollection();?>
<?php if($collection->count() > 0): ?>    
    <div class="cmsHomeInfoCard container-inner">
    <div class="row blogs">
    <?php foreach ($collection as $key => $data): ?>
        <?php  $string = strip_tags($data->getContent());
                    if (strlen($string) > 160) {
                        $stringCut = substr($string, 0, 160);
                        $endPoint = strrpos($stringCut, ' ');
                        $string = $endPoint? substr($stringCut, 0, $endPoint) : substr($stringCut, 0);
                        $string .= '...';
                    }
        ?>
       <div class="col-sm-3 box">
            <div class="card">
                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                    <img src="<?php echo $this->getMediaFolder().'/'. $data->getImage(); ?>" class="img-fluid">
                        <a href="#!">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><?php echo $data->getTitle(); ?></h5>
                        <p class="card-text"><?php echo $string; ?></p>
                    </div>
                    </div>
        </div>
        <?php endforeach; ?>  
        <?php else: ?>
    <h2>We couldn't find any records</h2>
<?php endif; ?>
</div>
        </div>

