<?php
/**
 * @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle
 * @var $viewModel Amasty\Promo\ViewModel\Product\View\Type\Bundle
 * @var $escaper Magento\Framework\Escaper
 */
$viewModel = $block->getViewModel();
$product = $block->getProduct();
$stripSelection = $product->getConfigureMode() ? true : false;
$options = $viewModel ? $block->decorateArray($viewModel->getOptions($product, $stripSelection)) : [];
?>
<?php if ($product->isSaleable()):?>
    <?php if (count($options)): ?>
        <script type="text/x-magento-init">
    {
        "#ampromo_items_form-<?= /* @noEscape */ $product->getId() ?>": {
            "priceBundle": {
                "optionConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                "controlContainer": ".field.option",
                "priceBoxSelector": ".price-base-price.tax"
            }
        }
    }
</script>
        <fieldset class="fieldset fieldset-bundle-options">
            <legend id="customizeTitle" class="legend title">
                <span>
                    <?= $escaper->escapeHtml(
                        __('Customize %1', $viewModel->getProductAttributeHtml($product, $product->getName(), 'name'))
                    ) ?>
                </span>
            </legend><br />
            <?= $block->getChildHtml('product_info_bundle_options_top') ?>
            <?php foreach ($options as $option): ?>
                <?= $option->getSelections() ? $viewModel->getOptionHtml($option, $product, $block) : '' ?>
            <?php endforeach; ?>
        </fieldset>
    <?php else: ?>
        <p class="empty"><?= $escaper->escapeHtml(__('No options of this product are available.')) ?></p>
    <?php endif; ?>
<?php endif;?>
<script>
    require(
        [
            'jquery',
            'Amasty_Promo/js/type/bundle'
        ], function($) {
            var popupOverlay = $('[data-role=ampromo-overlay]');

            popupOverlay.on('init.ampopup', function () {
                $('.fieldset-bundle-options').ampromoBundle({});
            });
        });
</script>
