<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$moduleName = $this->getRequest()->getModuleName();
$controllerName = $this->getRequest()->getControllerName();
$actionName = $this->getRequest()->getActionName();
$pageIdentifier = $moduleName . '_' . $controllerName . '_' . $actionName;
?>

<?php if ($crumbs && is_array($crumbs)) : ?>
    <div class="breadcrumbs">
        <div class="container-inner">
            <ul class="items">
                <?php $i = 0; ?>
                <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                    <li class="item <?php /* @escapeNotVerified */ echo $crumbName ?>">
                        <?php if ($crumbInfo['link']) : ?>
                            <a href="<?php /* @escapeNotVerified */
                                        echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
                                <?php echo $block->escapeHtml($crumbInfo['label']) ?>
                            </a>
                        <?php elseif ($crumbInfo['last']) : ?>
                            <strong><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
                        <?php else : ?>
                            <?php echo $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                    </li>
                    <?php $i++ ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

<?php endif; ?>