<?php $requisitionList = $block->getRequisitionList(); ?>
<?php $companyDetail = $block->getCompanyAndCustomerCode(); ?>
<?php $customerCode = isset($companyDetail['customer_code']) ? $companyDetail['customer_code'] : ''; ?>
<?php $companyName = isset($companyDetail['company_name']) ? $companyDetail['company_name'] : ''; ?>
<div class="orderTemplate">
    <div class="quoteTitle">
        <div class="columnTitle">
            <h2><?= __("Order templates for $companyName (Code: $customerCode)") ?></h2>
        </div>
    </div>

    <section id="elements">
        <ol class="collection collection-container">
            <!-- The first list item is the header of the table -->
            <li class="item item-container">
                <div class="attribute" data-name="Name"><?= __("Name") ?></div>
                <div class="attribute" data-name="Date"><?= __("Date") ?></div>
                <div class="attribute" data-name="Time"><?= __("Time") ?></div>
                <div class="attribute" data-name="Created"><?= __("Created") ?></div>
            </li>
            <?php foreach ($requisitionList as $item) { ?>
                <!-- The rest of the items in the list are the actual data -->
                <li class="item item-container" data-role="collapsible">
                    <div class="attribute" data-name="Name"><?= $item->getName() ?></div>
                    <div class="attribute" data-name="Date"><?= $block->getCreateDateFormat($item->getUpdatedAt()) ?></div>
                    <div class="attribute" data-name="Time"><?= $block->getCreateDateTimeFormat($item->getUpdatedAt()) ?></div>
                    <div class="attribute" data-name="Created"><?= $block->getCustomerName($item->getCustomerId()) ?></div>
                    <div class="attribute butContaner">
                        <div class="apply"><span>Apply</span></div>
                        <div class="show" data-role="trigger"><span> Show</span></div>
                        <div class="delete"><span>Delete</span></div>
                    </div>
                </li>
                <div class="resp-row-three" data-role="content">
                    <div class="row-three">
                        <ol class="collection collection-container">
                            <!-- The first list item is the header of the table -->
                            <li class="item item-sub-container">
                                <div class="attribute"></div>
                                <div class="attribute"></div>
                                <div class="attribute" data-name="Article no. Item description">Article no. Item
                                    description
                                </div>
                                <div class="attribute" data-name="stock"></div>
                                <div class="attribute " data-name="Quantity x pack. = Total QTY">Quantity x pack. =
                                    Total
                                    QTY
                                </div>
                                <div class="attribute" data-name="Packaging mark">Packaging mark</div>
                                <div class="attribute"></div>
                            </li>
                            <!-- The rest of the items in the list are the actual data -->
                            <?php $listItems = $block->getRequisitionListItems($item->getId()); ?>
                            <?php foreach ($listItems as $listItem) { ?>
                                <?php $product = $block->getProductBySku($listItem->getSku()); ?>
                                <?php if ($product) { ?>
                                    <?php $stockData = $block->getStockDataByProductCode($product, $listItem->getQty()); ?>
                                    <?php $stockColor = isset($stockData['color']) ? $stockData['color'] : ''; ?>
                                    <?php $availQty = isset($stockData['avail_qty']) ? $stockData['avail_qty'] : 0; ?>
                                    <?php $qty = (int) $listItem->getQty(); ?>
                                    <li class="item item-sub-container" data-role="collapsible">
                                        <div class="attribute"></div>
                                        <div class="attribute">
                                            <img src="<?= $block->getProductImage($product) ?>" >
                                        </div>
                                        <div class="attribute" data-name="Article no. Item description"><?= $product->getProductCode() ?> <br/>
                                            <?= $product->getName() ?>
                                        </div>
                                        <div class="attribute"><span class="<?= $stockColor ?>Box" id="stock-color-<?= $listItem->getId() ?>"></span></div>
                                        <div class="attribute" data-name="Quantity x pack. = Total QTY">
                                            <span class="boxContaner">
                                                <div id="<?= $listItem->getId() ?>-dec" class="decreaseQty icon-interface-minus" data-item-id="<?= $listItem->getId() ?>"></div>
                                                <input type="text"
                                                       class="qty-input"
                                                       id="qty-input-<?= $listItem->getId() ?>"
                                                       value="<?= $block->getQuantityUnitByQuantity($qty, $product) ?>"
                                                       data-item-id="<?= $listItem->getId() ?>"
                                                       data-availableqty="<?= $availQty ?>"
                                                >
                                                <div id="<?= $listItem->getId() ?>-upt" class="increaseQty icon-interface-plus" data-item-id="<?= $listItem->getId() ?>"></div>

                                                <span class="xpad">X</span>
                                                <input type="text" value="<?= $block->getMinimumAndMeasureQty($product) ?>" class="minimum-qty-<?= $listItem->getId() ?>" readonly>
                                                <span class="xpad">=</span>
                                                <input type="text" value="<?= $qty ?>" class="total-qty-<?= $listItem->getId() ?>" readonly>
                                            </span>
                                        </div>
                                        <div class="attribute pdPage">
                                            <span class="itembox"> </span>
                                            <?= (float) $product->getPackageBox() ?>
                                        </div>
                                        <div class="attribute"></div>
                                    </li>
                                <?php } ?>
                            <?php } ?>
                            <!-- The rest of the items in the list are the actual data -->
                        </ol>
                    </div>
                </div>
            <?php } ?>
        </ol>
    </section>
</div>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Wcb_RequisitionList/js/requisitionlist" : {}
        }
    }
</script>
