<script>
    require(['jquery', 'underscore'], function ($, _) {
        function attach() {
            var $cronExpressions = $('input.cron-expression, .cron-expression input[type="text"]');

            if ($cronExpressions.length) {
                require(['Mirasvit_Core/js/utils/cron-expression'], function (cron) {
                    $cronExpressions.each(function (key, el) {
                        cron(el);
                    })
                });
            }

            var $regularExpressions = $('input.regular-expression');

            if ($regularExpressions.length) {
                require(['Mirasvit_Core/js/utils/regular-expression'], function (regular) {
                    $regularExpressions.each(function (key, el) {
                        regular(el);
                    })
                });
            }
        }

        attach();

        var throttledAttach = _.throttle(attach, 100);

        var observer = new MutationObserver(throttledAttach);

        observer.observe(document.body, {
            subtree:   true,
            childList: true
        });
    })
</script>