<?php $collection = $block->getTestimonialsCollection(); 

if($collection->count() > 0): 
?>
 
<div class="carousel-wrap cmsHomeInfoCard container-inner testimonialContainer">
	<h2><?php echo __('What our customers say about Würth')?></h2>    
	<div class="owl-theme owl-testimonial carousel">
    <?php foreach ($collection as $key => $data): ?>
			<div class="item">
            <div class="testimonialWrapper">
						<div class="photo"><img src="<?php echo $this->getMediaFolder().'/'. $data->getImage(); ?>" class="mr-3"></div>
            <div class="media-body">
              <div class="testimonial">
                <p><?php echo $data->getContent();?></p>
                <span class="overview"><?php echo $data->getAuthor();?></span>
              </div>
            </div>
      </div>
		</div>
    	<?php endforeach; ?>
	</div>
</div>
<?php endif; ?>

<script type="text/javascript">
          /**
 * Created By : Rohan Hapani
 */
require(['jquery', 'owlcarousel'], function($) {
    $(document).ready(function() {
        $('.owl-testimonial').owlCarousel({
            loop: true,
            margin: 30,
            autoHeight: true,
            nav: true,
            navText: [
                "<i class='icon-interface-left'></i>",
                "<i class='icon-interface-right'></i>"
            ],
            autoplay: true,
            autoplayHoverPause: true,
            responsive: {
                0: {
                  items: 1
                },
                600: {
                  items: 1
                },
                1000: {
                  items: 2
                }
            }
        });
    });
});
        </script>
