
<div id="cart-item-form-section">


<?php
   /**
    * Copyright © Magento, Inc. All rights reserved.
    * See COPYING.txt for license details.
    */

   // phpcs:disable Magento2.Templates.ThisInTemplate

   /**  @var $block \Magento\Checkout\Block\Cart\Grid */

      $objmanager = \Magento\Framework\App\ObjectManager::getInstance();
      $session =  $objmanager->get("Magento\Checkout\Model\Session");
      $quote =$session->getQuote();
   ?>
<?php $mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>

<form action="<?= $block->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
   method="post"
   id="form-validate"
   data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
   {"validationURL" : "<?= $block->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
   "updateCartActionContainer": "#update_cart_action_container"}
   }'
   class="form form-cart chkcart">
   <?= $block->getBlockHtml('formkey') ?>
   <div class="cart table__wrap table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
      <?php if ($block->getPagerHtml()): ?>
      <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
         data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
      </div>
      <?php endif ?>
      <table id="shopping-cart-table"
         class="cart items data table cartTable"
         data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
         "updateCartActionContainer": "#update_cart_action_container"}}'>
         <caption class="table-caption"><?= $block->escapeHtml(__('Shopping Cart Items')) ?></caption>
         <thead class="table__header">
            <tr>
               <td class="totItem" colspan="8" class="totItem"><?= $block->escapeHtml(__('My Shopping bag')) ?> (<?php echo $qty = $quote->getItemsSummaryQty(); ?> <?php if ($qty <= 1) { echo 'item'; } else { echo 'items'; } ?>)

 </td>
            </tr>
            <tr class="itemFirst table__row">
               <th class="colitemphoto" scope="col" ><span><?= $block->escapeHtml(__('Item code and name')) ?></span></th>
               <th class="itemprice" scope="col"><span><?= $block->escapeHtml(__('Quantity X pieces = total quantity')) ?></span></th>
               <th class="itemjed" scope="col"><span><?= $block->escapeHtml(__('Jed. measure')) ?></span></th>
               <th class="itempricetype" scope="col"><span><?= $block->escapeHtml(__('Price type')) ?></span></th>
               <th class="itemprice with-vat" scope="col"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
               <th class="itemsubtotal without-vat" colspan="2" scope="col"><span><?= $block->escapeHtml(__('Amount without VAT')) ?></span></th>
               <th class="colact" scope="col"></th>
            </tr>
         </thead>
         <?php foreach ($block->getItems() as $_item): ?>
         <?= $block->getItemHtml($_item) ?>
         <?php endforeach ?>
      </table>
      <?php if ($block->getPagerHtml()): ?>
      <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
         data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?>
      </div>
      <?php endif ?>
   </div>
   <div class="cart main actions">
      <?php if ($block->getContinueShoppingUrl()): ?>
      <!--<a class="action continue"
         href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
         title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
      <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
      </a> -->
      <?php endif; ?>
      <?php if ($block->getViewModel()->isClearShoppingCartEnabled()): ?>
     <!-- <button type="button"
         name="update_cart_action"
         data-cart-empty=""
         value="empty_cart"
         title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
         class="action clear" id="empty_cart_button">
      <span><?= $block->escapeHtml(__('Clear Shopping Cart')) ?></span>
      </button> -->
      <?php endif ?>
      <div class="cart-act-icon">
          <span class="dIcons remove-cart-item" data-item-id="all">
             <img src=" <?php echo $block->getViewFileUrl('Magento_Checkout::images/delico.png'); ?>" />
         </span>
      </div>
     <!-- <button type="submit"
         name="update_cart_action"
         data-cart-item-update=""
         value="update_qty"
         title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
         class="action update">
      <span><?= $block->escapeHtml(__('Update Shopping Cart')) ?></span>
      </button>-->
      <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
   </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>

<script type="text/javascript">
require(['jquery'], function($) {
  $(".block .block-requisition-list").prependTo(".cart-act-icon");
  $("#negotiable-quote-form").prependTo(".cart-act-icon");
});
 </script>
</div>
