<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
$currentDirection = $block->getCurrentDirection();
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <?php if ($_key == 'price'){ continue; } ?>           
            <option value="<?= /* @escapeNotVerified */ $_key ?>&asc"
                <?php if ($block->isOrderCurrent($_key) && ($block->getCurrentDirection()=='asc' || $block->getCurrentDirection()=='' )): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?php if($_key =='name'){ ?>
                <?= $block->escapeHtml(__(ucfirst($_key))) ?> A to Z
                <?php } else { ?>
                    <?php if ($_order == 'Position'){ ?> 
                        Sort By
                        <?php } else { ?>           
                    <?= $block->escapeHtml(__(ucfirst($_order))) ?>  
                    <?php } ?>              
                <?php } ?>
                
            </option>
            <?php if ($_key == 'created_at'){ continue; } ?>
            <?php if ($_order == 'Position'){ continue; } ?>
            <option value="<?= /* @escapeNotVerified */ $_key ?>&desc"
                <?php if ($block->isOrderCurrent($_key) && $block->getCurrentDirection()=='desc'): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?php if($_key =='name'){ ?>
                <?= $block->escapeHtml(__(ucfirst($_key))) ?> Z to A
                <?php } else { ?>
                <?= $block->escapeHtml(__(ucfirst($_order))) ?>
                <?php } ?>
            </option>


        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?= /* @escapeNotVerified */ __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?= /* @escapeNotVerified */ __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>
