<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>

<?php if ($_orders && count($_orders)) : ?>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="mt-5">
            <div class="col-md-3  text-contaner">
                <div class="input-box"> <input type="text" class="form-control" id="searchInput"> <i class="fa fa-search"></i> </div>
            </div>

            <div class="col-md top-pager-contaner">
                <div class="order-products-toolbar toolbar bottom top-pager"><?= $block->getPagerHtml() ?></div>
            </div>
        </div>

    <?php endif ?>
    <div class="table-wrapper order-items order-detail">
        <table id="wcb-data-table" data-order="[]" class="table  table-bordered" style="width:100%">
            <thead class="wcb-first-row">
                <tr>
                    <th data-orderable="false" >Rb</th>
                    <th data-orderable="false" >Status</th>
                    <th style="width:18%">Name</th>
                    <th>Date</th>
                    <th style="width:12%">Online shop number</th>
                    <th style="width:12%">Internal order code</th>
                    <th>ERP Number</th>
                    <th data-orderable="false">Follow Order</th>
                    <th data-orderable="false"></th>
                </tr>
            </thead>
            <tbody>
                <?php $index=1; ?>
                <?php foreach ($_orders as $_order) : ?>
                <?php $customer = $this->LoadCustomerById($_order->getCustomerId()); ?>    
                    <tr>
                        <td data-th="RB"><?php echo $index; ?></div></td>
                        <td data-th="Status"><span class="green-box"></span></td>
                        <td data-th="Name"><?= $block->escapeHtml($customer->getName()); ?></td>
                        <td data-th="Date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <td data-th="Online shop number"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                        <td data-th="Internal order code"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                        <td data-th="ERP Number"><?= $block->escapeHtml($_order->getInternalOrderNumber()) ?></td>
                        <td data-th="Follow Order"><?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                                        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                                            ->getPostData($block->getReorderUrl($_order))
                                                        ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Follow Order')) ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Follow Order')) ?>"><a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="details-botton">Details</a></td>
                    </tr>
                <?php $index++; ?>
                <?php endforeach; ?>

            </tbody>
        </table>
    </div>

    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom bottom-pager"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>

<script>
    require(['jquery', 'dataTables'], function($, dt) {
        $('#wcb-data-table').DataTable( {
                          responsive: true,
                          language: { search: "" },
                          oLanguage: {
                              oPaginate: {
                                  sNext: '<span class="pagination-fa"><i class="fa fa-chevron-right" ></i></span>',
                                  sPrevious: '<span class="pagination-fa"><i class="fa fa-chevron-left"></i></span>'
                              }
                          }
                      } );
    });
</script>