<div class="undelivered-lines">
<div class="sales-title"> 
<?php echo __("Undelivered lines"); ?> 
</div>
<div class="filter-wrapper">
   <div class="row">
      <div class="col-md">
         <label class="filter">Filter</label> 
      </div>
   </div>
   <div class="row">
      <div class="col-md-6">
         <div class="row date-pad">
            <div class="col-md-6 date-fr">
               <label class="date-title">Date from:</label> 
               <input type="text" class="input-date date-from" id="date-from" placeholder="DD. MM. YYYY."  name="example-date" /><button type="button" class="ui-datepicker-trigger v-middle date-from"></button>               
            </div>
            <div class="col-md-6">
               <label class="date-titleto">To:</label> 
               <input type="text" class="input-date date-to" id="date-to" placeholder="DD. MM. YYYY." name="example-date" /><button type="button" class="ui-datepicker-trigger v-middle date-to"></button> 
            </div>
         </div>
         <div class="col-md-10 select-wrapper">
            <select class="form-select">
               <option selected>branch office (30793301 - ZAGREB)</option>
               <option value="1">One</option>
               <option value="2">Two</option>
               <option value="3">Three</option>
            </select>
         </div>
         <div class="col-md-6 select-wrapper">
              <button type="button" class="load-order">Load order</button>
         </div>
      </div>
     
   </div>
</div>


<div class="table-wrapper order-items order-detail">
        <table id="wcb-data-table" class="table  table-bordered" style="width:100%">
            <thead class="wcb-first-row">
                <tr>
                    <th  style="width:5%" data-orderable="false"><?= $block->escapeHtml(__('Rb')) ?></th>
                    <th style="width:8%" data-orderable="false"><?= $block->escapeHtml(__('Slika')) ?></th>
                    <th style="width:8%"><?= $block->escapeHtml(__('Br.art.')) ?></th>
                    <th style="width:15%"><?= $block->escapeHtml(__('Opis')) ?></th>
                    <th style="width:10%"><?= $block->escapeHtml(__('Naruceno')) ?></th>
                    <th style="width:10%"><?= $block->escapeHtml(__('Isporuceno')) ?></th>
                    <th style="width:10%"><?= $block->escapeHtml(__('Br. narudzbe')) ?></th>
                    <th style="width:12%"><?= $block->escapeHtml(__('Expected delivery date')) ?></th>
                    <th style="width:10%"><?= $block->escapeHtml(__('Datum narudzbe')) ?></th>
                    <th style="width:12%" data-orderable="false"></th>
                </tr>
            </thead>
            <tbody>
               <tr>
                  <td data-th="RB">1</td>
                  <td data-th="<?= $block->escapeHtml(__('Slika')) ?>"><span class="wcb-product-image"><img src="http://m2.wc.b2b.com/media/catalog/product/placeholder/default/replacement_product.png"></span></td>
                  <td data-th="<?= $block->escapeHtml(__('Br.art.')) ?>">6143130</td>
                  <td data-th="<?= $block->escapeHtml(__('Opis')) ?>">BIT-TEX30-CRVENI-1/4-L25MM</td>
                  <td data-th="<?= $block->escapeHtml(__('Naruceno')) ?>">20</td>
                  <td data-th="<?= $block->escapeHtml(__('Isporuceno')) ?>">0</td>
                  <td data-th="<?= $block->escapeHtml(__('Br. narudzbe')) ?>">25312/PP21-0088840</td>
                  <td data-th="<?= $block->escapeHtml(__('Expected delivery date')) ?>">25.05.2021</td>
                  <td data-th="<?= $block->escapeHtml(__('Datum narudzbe')) ?>">25.05.2021</td>
                  <td data-th=""><button type="button" class="cancel-order">Cancel order</button></td>
               </tr>
               <tr>
                  <td data-th="RB">2</td>
                  <td data-th="<?= $block->escapeHtml(__('Slika')) ?>"><span class="wcb-product-image"><img src="http://m2.wc.b2b.com/media/catalog/product/placeholder/default/replacement_product.png"></span></td>
                  <td data-th="<?= $block->escapeHtml(__('Br.art.')) ?>">8784637</td>
                  <td data-th="<?= $block->escapeHtml(__('Opis')) ?>">BIT-TEX30-CRVENI-1/4-L25MM</td>
                  <td data-th="<?= $block->escapeHtml(__('Naruceno')) ?>">30</td>
                  <td data-th="<?= $block->escapeHtml(__('Isporuceno')) ?>">0</td>
                  <td data-th="<?= $block->escapeHtml(__('Br. narudzbe')) ?>">25312/PP21-0088840</td>
                  <td data-th="<?= $block->escapeHtml(__('Expected delivery date')) ?>">25.05.2021</td>
                  <td data-th="<?= $block->escapeHtml(__('Datum narudzbe')) ?>">25.05.2021</td>
                  <td data-th=""><button type="button" class="cancel-order">Cancel order</button></td>
               </tr>
               <tr>
                  <td data-th="RB">3</td>
                  <td data-th="<?= $block->escapeHtml(__('Slika')) ?>"><span class="wcb-product-image"><img src="http://m2.wc.b2b.com/media/catalog/product/placeholder/default/replacement_product.png"></span></td>
                  <td data-th="<?= $block->escapeHtml(__('Br.art.')) ?>">8784637</td>
                  <td data-th="<?= $block->escapeHtml(__('Opis')) ?>">BIT-TEX30-CRVENI-1/4-L25MM</td>
                  <td data-th="<?= $block->escapeHtml(__('Naruceno')) ?>">40</td>
                  <td data-th="<?= $block->escapeHtml(__('Isporuceno')) ?>">256</td>
                  <td data-th="<?= $block->escapeHtml(__('Br. narudzbe')) ?>">25312/PP21-0088840</td>
                  <td data-th="<?= $block->escapeHtml(__('Expected delivery date')) ?>">27.05.2021</td>
                  <td data-th="<?= $block->escapeHtml(__('Datum narudzbe')) ?>">25.05.2021</td>
                  <td data-th=""><button type="button" class="cancel-order">Cancel order</button></td>
               </tr>

           </tbody>
      </table>
</div>

<script>
   require([
     'jquery',
     'mage/translate',
     'mage/calendar'
     ], function ($, $t) {
       $('.date-from').calendar({
         changeMonth: true,
         changeYear: true,
         showButtonPanel: true,
         currentText: $t('Go Today'),
         closeText: $t('Close'),
         showWeek: true
       });
     })
</script>
<script>
   require([
     'jquery',
     'mage/translate',
     'mage/calendar'
     ], function ($, $t) {
       $('.date-to').calendar({
         changeMonth: true,
         changeYear: true,
         showButtonPanel: true,
         currentText: $t('Go Today'),
         closeText: $t('Close'),
         showWeek: true
       });
     })
</script>

<script>
    require(['jquery', 'dataTables'], function($, dt) {
        $('#wcb-data-table').DataTable( {
                          responsive: true,
                          language: { search: "" },
                          oLanguage: {
                              oPaginate: {
                                  sNext: '<span class="pagination-fa"><i class="fa fa-chevron-right" ></i></span>',
                                  sPrevious: '<span class="pagination-fa"><i class="fa fa-chevron-left"></i></span>'
                              }
                          }
                      } );
    });
</script>
