<section class="container-inner registration-bg">
    <div class="row">
        <div class="col-md-5 textcenter"><img src="http://m2.wc.b2b.com/media/.thumbswysiwyg/Group_761.png?rand=1634815311" /></div>
        <div class="col-md-5 textCenterInMobile"><h2>Not registered yet, <span>Register now</span></h2>
            <p>and access more than 125000 products</p>
            <div class="primary-button">Registriraj se</div>

        </div>
    </div>
</section>