<?php $products = $block->getProducts(); ?>
<?php if (!empty($products)) { ?>
    <?php $categoriesData = isset($products["category_data"]) ? $products["category_data"] : []; ?>
    <?php $productsData = isset($products["product_data"]) ? $products["product_data"] : []; ?>
    <div class="section category-tab-wrapper">
        <div class="tab-title-contaner col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h2 class="tab-title">Maecenas scelerisque lacus ut sagittis pharetra. Maecenas cursus tincidunt gravida</h2>
            <p>Suspendisse vel quam dignissim, vulputate nibh id, tincidunt turpis. Maecenas scelerisque lacus ut sagittis pharetra. Maecenas cursus tincidunt gravida. Nam eleifend sapien sed nunc hendrerit, ut imperdiet </p>
        </div>
        <div class="tab-name" >
            <button class="btn btn-default filter-button active" data-filter="all">All Products</button>
            <?php foreach ($categoriesData as $categoryId => $category) { ?>
                <button class="btn btn-default filter-button" data-filter="<?= $categoryId ?>">
                    <?= $category ?>
                </button>
            <?php } ?>
        </div>
        <div class="row">
            <?php foreach ($productsData as $categoryId => $products) { ?>
                <?php foreach ($products as $product) { ?>
                    <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter <?= $categoryId; ?>">
                        <div class="img-responsive">
                            <img src="<?= $product["image"] ?>">
                        </div>
                        <h3><?= __($product["name"]); ?></h3>
                        <div class="btn">
                            <a href="<?= $product["product_url"]; ?>" target="_blank">
                                <button>Go to versions</button>
                            </a>
                        </div>
                    </div>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {

            $(".filter-button").click(function(){
                var value = $(this).attr('data-filter');

                if(value == "all")
                {
                    $('.filter').show('1000');
                }
                else
                {
                    $(".filter").not('.'+value).hide('3000');
                    $('.filter').filter('.'+value).show('3000');

                }
                if ($(".filter-button").removeClass("active")) {
                    $(this).removeClass("active");
                }
                $(this).addClass("active");
            });
        });
    </script>
<?php } ?>
