<!-- custom landing page cms part start -->
<!--<div class="custom-landing-page">
<div class="row">
   <div class="col-sm-7 order-sm-12">
      <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/tools.svg'); ?>" alt="tools"/>
   </div>
   <div class="col-sm-5 order-sm-1 left-text-contaner first-row">
      <div class="left-heading first">
         <h1>Lorem ipsum dolor <span>amet, consectetur</span> </h1>
      </div>
      <p>Mauris hendrerit semper quam, id dictum mauris pulvinar ac. In eu mi turpis. Mauris viverra hendrerit purus, eget laoreet tortor laoreet sed. Vivamus auctor id mi feugiat fringilla.</p>
   </div>
</div>
<div class="row">
   <div class="col-sm-6">
      <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/tools-2.svg'); ?>" alt="tools"/>
   </div>
   <div class="col-sm-6 right-text-contaner">
      <div class="heading">
         <h2>Maecenas scelerisque lacus ut sagittis pharetra. Maecenas cursus tincidunt gravida</h2>
      </div>
      <p class="center">Suspendisse vel quam dignissim, vulputate nibh id, tincidunt turpis. Maecenas scelerisque lacus ut sagittis pharetra. Maecenas cursus tincidunt gravida. Nam eleifend sapien sed nunc hendrerit, ut imperdiet</p>
      <ul>
         <li>
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/consult-1.svg'); ?>" alt="">
            <div class="text">
               <h3>Maecenas scelerisque lacus ut sagittis pharetra. </h3>
               <p>Suspendisse vel quam dignissim, vulputate nibh id, tincidunt turpis. Maecenas scelerisque lacus ut sagittis pharetra. Maecenas cursus tincidunt gravida. Nam eleifend sapien sed nunc hendrerit, ut imperdiet</p>
            </div>
         </li>
         <li>
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/consult-2.svg'); ?>" alt="">
            <div class="text">
               <h3>Maecenas scelerisque lacus ut sagittis pharetra. </h3>
               <p>Suspendisse vel quam dignissim, vulputate nibh id, tincidunt turpis. Maecenas scelerisque lacus ut sagittis pharetra. Maecenas cursus tincidunt gravida. Nam eleifend sapien sed nunc hendrerit, ut imperdiet</p>
            </div>
         </li>
         <li>
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/consult-3.svg'); ?>" alt="">
            <div class="text">
               <h3>Maecenas scelerisque lacus ut sagittis pharetra. </h3>
               <p>Suspendisse vel quam dignissim, vulputate nibh id, tincidunt turpis. Maecenas scelerisque lacus ut sagittis pharetra. Maecenas cursus tincidunt gravida. Nam eleifend sapien sed nunc hendrerit, ut imperdiet</p>
               <div class="btn">
                  <a href="#"><button>Go to product</button></a>
               </div>
            </div>
         </li>
      </ul>
   </div>
   <div class="col-sm-6 order-sm-12">
      <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/tools-3.svg'); ?>" alt="tools"/>
   </div>
   <div class="col-sm-6 order-sm-1 left-text-contaner">
      <div class="left-heading">
         <h2>Mauris hendrerit semper quam, id dictum mauris pulvinar ac. In eu mi turpis.</h2>
      </div>
      <p class="redtext">Mauris hendrerit semper quam, id dictum mauris pulvinar ac. In eu mi turpis mauris viverra hendrerit puru</p>
      <p class="center"> ivamus auctor id mi feugiat fringilla.Mauris hendrerit semper quam, id dictum mauris pulvinar ac. In eu mi turpis. Mauris viverra hendrerit purus, eget laoreet tortor laoreet sed. Vivamus auctor id mi feugiat fringilla.Mauris hendrerit semper quam, id dictum mauris pulvinar ac. In eu mi turpis. Mauris viverra hendrerit purus, eget laoreet tortor laoreet sed. Vivamus auctor id mi feugiat fringilla.</p>
   </div>
</div> -->
<!-- custom landing page cms part end -->
<div class="section category-tab-wrapper">
   <div class="tab-title-contaner col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h2 class="tab-title">Maecenas scelerisque lacus ut sagittis pharetra. Maecenas cursus tincidunt gravida</h2>
      <p>Suspendisse vel quam dignissim, vulputate nibh id, tincidunt turpis. Maecenas scelerisque lacus ut sagittis pharetra. Maecenas cursus tincidunt gravida. Nam eleifend sapien sed nunc hendrerit, ut imperdiet </p>
   </div>
   <div class="tab-name" >
      <button class="btn btn-default filter-button active" data-filter="all">All Products</button>
      <button class="btn btn-default filter-button" data-filter="hdpe">Akumulatorski alati</button>
      <button class="btn btn-default filter-button" data-filter="sprinkle">Pneumatski alati</button>
      <button class="btn btn-default filter-button" data-filter="spray">Električni alati</button>
      <button class="btn btn-default filter-button" data-filter="irrigation">Strojevi općeniti - Pribor</button>
   </div>
   <div class="row">
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter hdpe">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-1.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter hdpe">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-2.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter hdpe">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-3.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter sprinkle">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-1.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter sprinkle">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-2.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter spray">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-3.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter spray">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-4.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter spray">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-1.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter irrigation">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-2.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter irrigation">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-3.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter irrigation">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-4.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
      <div class="gallery_product col-lg-3 col-md-4 col-sm-3 col-xs-6 filter irrigation">
         <div class="img-responsive">
            <img src="<?php echo $block->getViewFileUrl('Magento_Cms::images/product-1.svg'); ?>">
         </div>
         <h3>UREĐAJI ZA ISTISKIVANJE - AKUMULATORSKI</h3>
         <div class="btn">
            <a href="#"><button>Go to versions</button></a>
         </div>
      </div>
   </div>
</div>
<script type="text/javascript">
   require([
       'jquery'
   ], function ($) { 
   
   $(".filter-button").click(function(){
   var value = $(this).attr('data-filter');
   
   if(value == "all")
   {   
   $('.filter').show('1000');
   }
   else
   {
   $(".filter").not('.'+value).hide('3000');
   $('.filter').filter('.'+value).show('3000');
   
   }
   
   if ($(".filter-button").removeClass("active")) {
   $(this).removeClass("active");
   }
   $(this).addClass("active");
   });
   
   
   
   });
</script>