<!-- recommended serach html start -->
<div class="recommended-search">
   <div class="search-heading">
      <h3>Last search</h3> 
   </div>
   <ul class="row search-botton-contaner">
      <li class="active"><a href="#">Advertising materials</a></li>
      <li><a href="#">Automobile</a></li>
      <li><a href="#">Tools</a></li>
      <li><a href="#">Direct Mounting</a></li>
      <li><a href="#">Fire Protection</a></li>
   </ul>
   <div class="search-heading">
      <h3>Last Seen</h3>
   </div>
   <div class="row search-contaner">
      <div class="col-2">
         <div  class="search-pro-img">
            <img src="http://m2.wc.b2b.com/media/catalog/product/cache/727b38be8af09735bb0416b905d0115c/w/g/wg02-bk-0.jpg" alt="Card image cap"> 
         </div>
         <div class="search-pro-title">
            <p> Dijagnostika za motorna vozila WOW </p>
         </div>
      </div>
      <div class="col-2">
         <div  class="search-pro-img">
            <img src="http://m2.wc.b2b.com/media/catalog/product/cache/727b38be8af09735bb0416b905d0115c/w/g/wg02-bk-0.jpg" alt="Card image cap"> 
         </div>
         <div class="search-pro-title">
            <p>Direktna montaža</p>
         </div>
      </div>
      <div class="col-2">
         <div  class="search-pro-img">
            <img  src="http://m2.wc.b2b.com/media/catalog/product/cache/727b38be8af09735bb0416b905d0115c/w/g/wg02-bk-0.jpg" alt="Card image cap"> 
         </div>
         <div class="search-pro-title">
            <p>Elektroinstalacije</p>
         </div>
      </div>
      <div class="col-2">
         <div  class="search-pro-img">
            <img  src="http://m2.wc.b2b.com/media/catalog/product/cache/727b38be8af09735bb0416b905d0115c/w/g/wg02-bk-0.jpg" alt="Card image cap"> 
         </div>
         <div class="search-pro-title">
            <p>Elementi za spajanje (opći, metrički, colni) </p>
         </div>
      </div>
      <div class="col-2">
         <div  class="search-pro-img">
            <img  src="http://m2.wc.b2b.com/media/catalog/product/cache/727b38be8af09735bb0416b905d0115c/w/g/wg02-bk-0.jpg" alt="Card image cap">  
         </div>
         <div class="search-pro-title">
            <p>Građevinska oprema i pribor</p>
         </div>
      </div>
      <div class="col-2">
         <div  class="search-pro-img">
            <img  src="http://m2.wc.b2b.com/media/catalog/product/cache/727b38be8af09735bb0416b905d0115c/w/g/wg02-bk-0.jpg" alt="Card image cap"> 
         </div>
         <div class="search-pro-title">
            <p>Elementi za spajanje (opći, metrički, colni)</p>
         </div>
      </div>
   </div>
</div>
<!-- recommended serach html start -->


<!-- product serach dropdown html start-->
<br/> <br/> <br/> <br/>
<h3>Product serach dropdown html start</h3>
<div class="recommended-search">
   <div class="row">
      <div class="col-md-6 prodcut-dropdown-search">
         <h3 class="cat-count">Number of products found: 130,850</h3>
         <div class="table-contaner">
            <table>
               <tr>
                  <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                  <td><a href="#">Akumulatorski alati</a></td>
                  <td>430</td>
               </tr>
               <tr>
                  <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                  <td><a href="#">DT SERIES - WEDGE FOR TWO-POLE PLUG  HOUSING</a></td>
                  <td>45</td>
               </tr>
               <tr>
                  <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                  <td><a href="#">DT SERIES - WEDGE FOR THREE-POLE  HOUSING</a></td>
                  <td>100</td>
               </tr>
               <tr>
                  <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                  <td><a href="#">DT SERIJA - KLIN ZA UTIČNO KUĆIŠTE  DVOPOLNO  </a></td>
                  <td>345</td>
               </tr>
               <tr>
                  <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                  <td><a href="#">STROJ.NAREZ.SVRDLO-DIN371-C-HSSE-ŽUT- M6-ZEBRA</a></td>
                  <td>35</td>
               </tr>
               <tr>
                  <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                  <td><a href="#">DT SERIES - WEDGE FOR TWO-POLE PLUG  HOUSING</a></td>
                  <td>23</td>
               </tr>
               <tr>
                  <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                  <td><a href="#">DT SERIES - WEDGE FOR THREE-POLE  HOUSING</a></td>
                  <td>34</td>
               </tr>
            </table>
         </div>
      </div>
      <div class="col-md-6">
         <h3 class="cat-count">Matching product categories</h3>
         <div class="table-contaner">
            <table>
               <tr>
                  <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                  <td><a href="#">Akumulatorski alati</a></td>
               </tr>
               <tr>
                  <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                  <td><a href="#">DT SERIES - WEDGE FOR TWO-POLE PLUG  HOUSING</a></td>
               </tr>
               <tr>
                  <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                  <td><a href="#">DT SERIES - WEDGE FOR THREE-POLE  HOUSING</a></td>
               </tr>
            </table>
         </div>
         <div class="cms-cat-title">
            <h3 class="cat-count">from CMS pages</h3>
            <div class="table-contaner">
               <table>
                  <tr>
                     <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                     <td><a href="#">Alati (akumulatorski, pneumatski, elektro, motorni)</a></td>
                  </tr>
                  <tr>
                     <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                     <td><a href="#">Alati (akumulatorski, pneumatski, elektro, motorni)</a></td>
                  </tr>
                  <tr>
                     <td> <img src="http://m2.wc.b2b.com/static/version1649218523/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/thumbnail.jpg" alt="Category" width="24px" height="24px"></td>
                     <td><a href="#">Alati (akumulatorski, pneumatski, elektro, motorni)</a></td>
                  </tr>
               </table>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- product serach dropdown html start-->