<div class="row wcb-we-meet">
   <div class="col-md-4">
        <div class="wcb-search-wrap">					
						
                        <form class="wcb-form-minisearch"  action="#" method="get">
                            <div class="wcb-field-search">
                                <input id="wcb-search" type="text" name="wcb-search" value="" placeholder="Search a location" class="wcb-input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" aria-expanded="true" autocomplete="off">      
                                
                                <button type="submit" title="Search" class="wcb-search-button">
                                </button>
                            </div>
                            
                        </form>
        </div>
    </div>

    <div class="col-md-8">
        <div class="infoCard">
        <iframe src="https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d1890.9425701512962!2d73.73652250788994!3d18.579216339268793!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m0!4m5!1s0x3bc2b94017c28d93%3A0x4e6a714b7fbabc51!2sWurth%20Information%20Technology%20India%20Pvt%20Ltd.%2C%20Blue%20Ridge%20Town%20Pune%2C%20Phase%201%2C%20Hinjewadi%20Rajiv%20Gandhi%20Infotech%20Park%2C%20Hinjawadi%2C%20Pimpri-Chinchwad%2C%20Maharashtra%20411057!3m2!1d18.578141!2d73.73921109999999!5e0!3m2!1sen!2sin!4v1654856987363!5m2!1sen!2sin" width="700" height="550" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
               
        </div>
    </div>

</div>


<div class="row">
   <div class="col-md-8">
        <div class="infoCard">
            <img src="https://devtestb2b.wuerth.com.hr/media/wysiwyg/image_142_1.png" class="img-fluid">
                
        </div>
    </div>

    <div class="col-md-4">
        <div class="infoCard">
        <p><span class="wcb-cms-location"></span>Zagreb</p>
        <p><span class="wcb-cms-location"></span>Zagreb</p>
        <p><span class="wcb-cms-location"></span>Zagreb</p>
        <p><span class="wcb-cms-location"></span>Zagreb</p>
        <p><span class="wcb-cms-location"></span>Zagreb</p>
        <p><span class="wcb-cms-location"></span>Zagreb</p>
       
        </div>
    </div>

</div>