<div class="row wcb-wholesale">
   <div class="col-md-4">
        <div class="infoCard">
            <img src="https://devtestb2b.wuerth.com.hr/media/wysiwyg/image_117_1_.png" class="img-fluid">
                <div class="wcb-content">
                        <h3>Jankomir</h3>
                        <p>Kovinska 3/<br>
                            10 090 Zagreb
                        </p>
                        <p class="wcb-cms-location-wrapper"><span class="wcb-cms-location"></span>Location >></p>
                        <p><span class="icon-com-phone-a"></span> Phone: 01 5604 566 <br>
                         <span class="icon-wuerth-e-mail"></span> E-Mail:  shop_jankomir@wuerth.com.hr</p>
                        <p><strong>Working hours:</strong> Mon. - Five. 7.00 - 16.00 h </p>
                </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="infoCard">
            <img src="https://devtestb2b.wuerth.com.hr/media/wysiwyg/image_118_1_.png" class="img-fluid">
                <div class="wcb-content">
                        <h3>Jankomir</h3>
                        <p>Kovinska 3/<br>
                            10 090 Zagreb
                        </p>
                        <p class="wcb-cms-location-wrapper"><span class="wcb-cms-location"></span>Location >></p>
                        <p><span class="icon-com-phone-a"></span> Phone: 01 5604 566 <br>
                         <span class="icon-wuerth-e-mail"></span> E-Mail:  shop_jankomir@wuerth.com.hr</p>
                        <p><strong>Working hours:</strong> Mon. - Five. 7.00 - 16.00 h </p>
                </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="infoCard">
            <img src="https://devtestb2b.wuerth.com.hr/media/wysiwyg/image_119_1_.png" class="img-fluid">
                <div class="wcb-content">
                        <h3>Jankomir</h3>
                        <p>Kovinska 3/<br>
                            10 090 Zagreb
                        </p>
                        <p class="wcb-cms-location-wrapper"><span class="wcb-cms-location"></span>Location >></p>
                        <p><span class="icon-com-phone-a"></span> Phone: 01 5604 566 <br>
                         <span class="icon-wuerth-e-mail"></span> E-Mail:  shop_jankomir@wuerth.com.hr</p>
                        <p><strong>Working hours:</strong> Mon. - Five. 7.00 - 16.00 h </p>
                </div>
        </div>
    </div>
</div>