<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php $level = $this->getCurrentCategory()->getLevel(); ?>
<?php $ProductCount = $this->getCurrentCategory()->getProductCollection()->Count(); ?>
<?php $catId = $this->getCurrentCategory()->getId(); ?>

<?php $subcategories = [] ;?>

<?php $subcategories = $block->getCategoryChildrenData($catId); ?>
<?php if(count($subcategories) > 0): ?>
    <div class="products wrapper grid products-grid">
        <ol class="products list items product-items">
            <?php foreach($subcategories as $subcategory): ?>
                <?php $subcategory = $block->getCategoryData($subcategory->getId()); ?>
                <?php if($subcategory): ?>
                <li class="item product product-item">
                    <div class="product-item-info">
                        <?php if ($_imgUrl = $subcategory->getImageUrl()): ?>
                            <a href="<?= $subcategory->getUrl() ?>" class="product photo product-item-photo">
                                <span class="product-image-container">
                                    <?php $_imgHtml = '<img src="' . $_imgUrl . '" />'; ?>
                                    <?php echo $_imgHtml = $this->outPutHelper->categoryAttribute($subcategory, $_imgHtml, 'image'); ?>
                                </span>
                            </a>
                        <?php endif; ?>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link" href="<?= $subcategory->getUrl() ?>"><?= $subcategory->getName() ?></a>
                            </strong>
                            <?php if($level > 3 && $ProductCount > 1) { ?>
                            <span><label><?php echo $ProductCount ; ?> variations</label></span>
                            <?php }  ?>

                        </div>
                    </div>
                </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
    </div>
<?php else: ?>
    <?php if (!$block->isContentMode() || $block->isMixedMode()): ?>
        <?= $block->getProductListHtml() ?>
    <?php endif; ?>
<?php endif; ?>
