<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
/**
 * Existing User account creation form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
?>
<?php
/** @var \Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $block->getData('addressHelper');
/** @var \Magento\Directory\Helper\Data $directoryHelper */
$directoryHelper = $block->getData('directoryHelper');

$formData = $block->getFormData();
?>
<div class="row">
<form class=" form create account form-create-account exUserregistration"
      action="<?php echo $block->getUrl("excustomer/account/createpost"); ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off" data-mage-init='{"validation":{}}' >

 <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
    <?= /* @noEscape */ $block->getChildHtml('form_fields_before_in_form') ?>
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
    <fieldset class="fieldset create info col-md-7">
        <div class="page-title-wrapper">
        <h1 class="page-title"><span><?= $block->escapeHtml(__('User Registration for existing customer')) ?></span></h1></div>        <div class="field vat-tax-id _required">
            <label class="label" for="vat_tax_id">
                <span><?= $block->escapeHtml(__('Company OIB')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[vat_tax_id]" id="vat_tax_id"
                       value=""
                       data-validate="{required:true}"
                       title="<?= $block->escapeHtmlAttr(__('Company OIB')) ?>"
                       class="input-text validate-length minimum-length-11 maximum-length-20">
            </div>
        </div>
        <div class="field company-name _required">
            <label class="label" for="company_name">
                <span><?= $block->escapeHtml(__('Company Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[company_name]" id="company_name"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Compmmany Name')) ?>"
                       class="input-text" data-validate="{required:true}" disabled='true'>
            </div>
        </div>

        <div class="field customer-code _required">
            <label class="label" for="customer_code">
                <span><?= $block->escapeHtml(__('Customer Code')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[customer_code]" id="customer_code"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Customer Code')) ?>"
                       class="input-text validate-number" data-validate="{required:true}">
            </div>
        </div>

        <div class="field confirm-customer-code _required">
            <label class="label" for="confirm_customer_code">
                <span><?= $block->escapeHtml(__('Confirm Customer Code')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[confirm_customer_code]" id="confirm_customer_code"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Confirm Company Name')) ?>"
                       class="input-text"
                       data-validate="{required:true, equalTo:'#customer_code'}" disabled='true'>
            </div>
        </div>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>"/>
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>"/>
      
<div id="link-error"></div>
        <div class="field field-name-firstname _required">
            <label class="label" for="firstname"><span><?php echo __("First Name")?></span></label>
            <div class="control">
                <input type="text" id="firstname"
                       name="firstname"
                       value=""
                       title="firstname"
                       class="input-text letters-only " data-validate="{required:true}">
            </div>
        </div>

        <div class="field field-name-lastname _required">
            <label class="label" for="lastname"><span><?php echo __("Last Name")?></span></label>
            <div class="control">
                <input type="text" id="lastname"
                       name="lastname"
                       value=""
                       title="lastname"
                       class="input-text letters-only " data-validate="{required:true}">
            </div>
        </div>

<div class="field password _required">
<label for="password" class="label"><span><?= $escaper->escapeHtml(__('Password')) ?></span></label>
    <div class="control">
        <input type="password" name="password" id="password"
                title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>"
                class="input-text"
                data-password-min-length="<?=
                $escaper->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                data-password-min-character-sets="<?=
                $escaper->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                data-validate="{required:true, 'validate-customer-password':true}"
                autocomplete="off">
        <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
            <div id="password-strength-meter" class="password-strength-meter">
                <?= $escaper->escapeHtml(__('Password Strength')) ?>:
                <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                    <?= $escaper->escapeHtml(__('No Password')) ?>
                </span>
            </div>
        </div>
    </div>
</div>
      
        <div class="field confirmation _required">
            <label for="password-confirmation" class="label">
                <span><?= $escaper->escapeHtml(__('Confirm Password')) ?></span>
            </label>
            <div class="control">
                <input type="password"
                       name="password_confirmation"
                       title="<?= $escaper->escapeHtmlAttr(__('Confirm Password')) ?>"
                       id="password-confirmation"
                       class="input-text"
                       data-validate="{required:true, equalTo:'#password'}"
                       autocomplete="off">
            </div>
        </div>
<div class="field _required">
            <label for="email_address" class="label"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email"
                       name="email"
                       autocomplete="email"
                       id="email_address"
                       value="<?= $escaper->escapeHtmlAttr($formData->getEmail()) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>

        <div class="field _required">
            <label for="confirm_email_address" class="label"><span><?= $escaper->escapeHtml(__('Confirm Email')) ?></span></label>
            <div class="control">
                <input type="email"
                       name="confirm_email"
                       autocomplete="email"
                       id="confirm_email_address"
                       value="<?= $escaper->escapeHtmlAttr($formData->getEmail()) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('Confirm Email')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true, 'validate-email':true,equalTo:'#email_address'}">
            </div>
        </div>
        
        <div class="field name _required">
            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Telephone')) ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="Telephone" value="" class="input-text validate-number"
                        type="text" data-validate="{required:true}">
            </div>
        </div>
            <div class="field position _required">
            <label for="position" class="label">
                <span><?= $escaper->escapeHtml(__('Position in the Company')) ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="position"
                       title="<?= $escaper->escapeHtmlAttr(__('Position in the Company')) ?>"
                       id="position"
                       class="input-text"
                       data-validate="{required:true}"
                       autocomplete="off">
            </div>
        </div>
                     
        <div class="field choice newsletterAcceptance">
            <label for="is_subscribed" class="label newsletter">
            <input type="checkbox"
                   name="is_subscribed"
                   title="<?= $block->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>"
                   value="1"
                   id="is_subscribed"
                <?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                   class="checkbox"/>
                   <span class="checkmark"> </span>
            
                <span><?= $block->escapeHtml(__('Sign Up for Newsletter')) ?></span>
            </label>
        </div>
            <?php /* Extensions placeholder */ ?>
            <?= $block->getChildHtml('customer.form.register.newsletter') ?>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?= $block->getChildHtml('form.additional.info') ?>
        <div class="form-group required ">
            <label for="privacy_policy" class="newsletter">
            <input type="checkbox" id="privacy_policy" name="privacy_policy" value="1" title="<?php echo 'Accept the privacy policy' ?>" class="checkbox required-entry">
            <span class="checkmark"> </span>
            <?php echo 'Accept the privacy policy' ?> (<a href="javascript:void(0)" id="privacy-policy-ex"><?php echo 'privacy policy'; ?></a>)</label>
            </div>
        <div class="actions-toolbar ">
            <button type="submit" id="confirm-reg"
                    class="action submit primary-button btn160 "
                    title="<?= $block->escapeHtmlAttr(__('Confirm')) ?>">
                <span><?= $block->escapeHtml(__('Confirm')) ?></span>
            </button>
        </div>
        <div id="popup-modal" style="display:none;">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('privacy-login')->toHtml();?>
        </div>
    </fieldset>    
</form>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_CustomerCustomAttributes/validation": {
                "mixins": [
                    "Magento_CustomerCustomAttributes/error-placement",
                    "Magento_CustomerCustomAttributes/validation-ignore"
                ]
            },
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        },
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($, modal) {
            $("#privacy-policy-ex").click(function(e){
                var popup = modal(options, $('#popup-modal'));
                $('#popup-modal').modal('openModal');
            });
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Custom Form Popup',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
        }
    );
</script>
<?php
$ajaxurl = $block->getUrl('excustomer/account/checkcompany');
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Wcb_CustomerRegistration/js/companyoib": {
                    "AjaxUrl": "<?php echo $ajaxurl; ?>"
                }
            }
        }
</script>