<div class="row">
    <div class="col-md-7">
    <form class="form create account form-create-account newUserRegistration" action="<?= $escaper->escapeUrl($block->getUrl('excustomer/account/newcustomercreate')) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Please fill all Required Fields')) ?>"  onSubmit="return checkCaptcha() ;" data-mage-init='{"validation":{}}' >
            <fieldset class="fieldset">
                 <div class="formSections">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('About the company')) ?></span></legend>
                    <div class="field vat-tax-id _required">
                        <label class="label" for="vat_tax_id">
                            <span><?= $block->escapeHtml(__('Company OIB')) ?></span>
                        </label>
                        <div class="control">
                            <input type="text" name="company[vat_tax_id]" id="vat_tax_id" value="" title="<?= $block->escapeHtmlAttr(__('Company OIB')) ?>" class="input-text validate-length minimum-length-11 maximum-length-11" data-validate="{required:true}">
                        </div>
                    </div>
                    <p id="link-error"></p>
                    <div class="field company-name _required">
                        <label class="label" for="company_name">
                            <span><?= $block->escapeHtml(__('Company Name')) ?></span>
                        </label>
                        <div class="control">
                            <input type="text" name="company[company_name]" id="company_name" value="" title="<?= $block->escapeHtmlAttr(__('Company Name')) ?>" class="input-text validate-alpha" data-validate="{required:true}">
                        </div>
                    </div>

                    <div class="field no_of_employees _required">
                        <label class="label" for="no_of_employees">
                            <span><?= $block->escapeHtml(__('Number of Employees')) ?></span>
                        </label>
                        <div class="control">
                            <input type="text" name="company[no_of_employees]" id="no_of_employees" value="" title="<?= $block->escapeHtmlAttr(__('Number of Employees')) ?>" class="input-text validate-number" data-validate="{required:true}">
                        </div>
                    </div>

                    <?php 
                        $blockObj= $block->getLayout()->createBlock('Wcb\CustomerRegistration\Block\CustomerRegistration');
                        $customerGroups =  $blockObj->getCustomerGroups();
                        $label = array_column($customerGroups, 'label');
                        $value = array_column($customerGroups, 'value');
                        $resultArray = array_combine($value, $label);
                    ?>
                    <div class="field company-division _required">
                        <label class="label" for="division">
                            <span><?= $block->escapeHtml(__('Division')) ?></span>
                        </label>
                        <div class="control">
                            <select name='company[division]' class='form-control' data-validate="{required:true}">
                                <option value=""><?php echo __("Please select Division")?></option>
                                <?php foreach($resultArray as $key => $value){?>                                    
                                <option value="<?php echo $key;?>"><?php echo $value ?></option>
                                        <?php }?>
                            </select>
                        </div>
                    </div>

                    <div class="field company-activities _required">
                        <label class="label" for="activities">
                            <span><?= $block->escapeHtml(__('Activities')) ?></span>
                        </label>
                        <div class="control">
                        <select name='company[activities]' class='form-control' data-validate="{required:true}">
                            <option value=""><?php echo __("Please select Activities")?></option>
                            <option value="<?php echo 'ds'?>"><?php echo 'Activity 1' ?></option>
                        </select>
                        </div>
                    </div>
                </div>
                 <div class="formSections">
        
                    <legend class="legend"><?php echo __("Address")?></legend>
        
                    <div class="field company-country _required">
                        <label class="label" for="country">
                            <span><?= $block->escapeHtml(__('Country')) ?></span>
                        </label>
                        <div class="control">
                        <?php $countryBlock = $block->getLayout()->createBlock('Magento\Directory\Block\Data');?>
                        <?= $countryBlock->getCountryHtmlSelect($defValue = "HR", $name = "country_id", $id = "country", $title = 'Country');?>
                        </div>
                    </div>

                    <div class="field company-street _required">
                        <label class="label" for="street">
                            <span><?= $block->escapeHtml(__('Address')) ?></span>
                        </label>
                        <div class="control">
                            <input type="text" name="company[street]" id="street" value=""                                title="<?= $block->escapeHtmlAttr(__('Street')) ?>" class="input-text" data-validate="{required:true}">
                        </div>
                    </div>

                    <div class="field company-city _required">
                        <label class="label" for="city">
                            <span><?= $block->escapeHtml(__('City')) ?></span>
                        </label>
                        <div class="control">
                            <input type="text" name="company[city]" id="city" value="" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="input-text" data-validate="{required:true}">
                        </div>
                    </div>

                    <div class="field company-region _required">
                        <label class="label" for="region">
                            <span><?= $block->escapeHtml(__('Region')) ?></span>
                        </label>
                        <div class="control">
                        <?php 
                            $blockObjs = $block->getLayout()->createBlock('Wcb\CustomerRegistration\Block\CustomerRegistration');
                            $regions =  $blockObjs->getRegionsOfCountry('HR');         
                            $regionLabel = array_column($regions, 'label');
                            $regionValue = array_column($regions, 'value');
                            $regionArray = array_combine($regionValue, $regionLabel);
                            ?>
                            <select class="form-control" name="region" id="region">
                                <?php foreach($regionArray as $key => $value){?>                            
                                    <option value="<?php echo $key;?>"><?php echo $value ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </div>

                    <div class="field company-postcode _required">
                        <label class="label" for="postcode">
                            <span><?= $block->escapeHtml(__('Zipcode')) ?></span>
                        </label>
                        <div class="control">
                            <input type="text" name="company[postcode]" id="postcode" value="" title="<?= $block->escapeHtmlAttr(__('Zipcode')) ?>" class="input-text" data-validate="{required:true}">
                        </div>
                    </div>
                </div>

                 <div class="formSections">
        
                    <legend class="legend"><?php echo __("About the user")?></legend>
       
                    <div class="field field-name-firstname _required">
                        <label class="label" for="firstname"><span><?php echo __("First Name")?></span></label>
                        <div class="control">
                            <input type="text" id="firstname" name="firstname" value="" title="firstname" class="input-text validate-alpha" data-validate="{required:true}">
                        </div>
                    </div>

                    <div class="field field-name-lastname _required">
                        <label class="label" for="lastname"><span><?php echo __("Surname")?></span></label>
                        <div class="control">
                            <input type="text" id="lastname" name="lastname" value="" title="surname" class="input-text validate-alpha" data-validate="{required:true}">
                        </div>
                    </div>
                    
                    <fieldset class="fieldset create account" data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
                    <div class="field _required">
                        <label for="email_address" class="label"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input type="email" name="email" autocomplete="email" id="email_address" value=""                       title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>

                    <div class="field _required">
                        <label for="confirm_email_address" class="label"><span><?= $escaper->escapeHtml(__('Confirm Email')) ?></span></label>
                        <div class="control">
                            <input type="email" name="confirm_email" autocomplete="email" id="confirm_email_address" value=""title="<?= $escaper->escapeHtmlAttr(__('Confirm Email')) ?>" class="input-text" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true,equalTo:'#email_address'}">
                        </div>
                    </div>

                    <div class="field position _required">
                        <label for="position" class="label">
                            <span><?= $escaper->escapeHtml(__('Position in the Company')) ?></span>
                        </label>
                        <div class="control">
                            <input type="text" name="position" title="<?= $escaper->escapeHtmlAttr(__('Position in the Company')) ?>" id="position" class="input-text validate-alpha" data-validate="{required:true}" autocomplete="off">
                        </div>
                    </div>

                    <div class="field password _required">
                        <label for="password" class="label"><span><?= $escaper->escapeHtml(__('Password')) ?></span></label>
                        <div class="control">
                            <input type="password" name="password" id="password" title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>" class="input-text" data-password-min-length="<?= $escaper->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>" data-password-min-character-sets="<?= $escaper->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>" data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off">
                            <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                                <div id="password-strength-meter" class="password-strength-meter">
                                    <?= $escaper->escapeHtml(__('Password Strength')) ?>:
                                    <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                        <?= $escaper->escapeHtml(__('No Password')) ?>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
      
                    <div class="field confirmation _required">
                        <label for="password-confirmation" class="label">
                            <span><?= $escaper->escapeHtml(__('Confirm Password')) ?></span>
                        </label>
                        <div class="control">
                            <input type="password" name="password_confirmation" title="<?= $escaper->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                        </div>
                    </div>
                    <div class="field name">
                        <label class="label" for="telephone"><span><?= $block->escapeHtmlAttr(__('Phone')) ?></span></label>
                        <div class="control">
                            <input name="telephone" id="telephone" title="Phone" value="" class="input-text validate-number" type="text" data-validate="{required:false}">
                        </div>
                    </div>
                </div>

                 <div class="formSections">
                    <legend class="legend"><?php echo __("Delivery Address")?></legend>
        
                    <div class="field same_as_hq_address">
                        <div class="control">
                            <input type="checkbox" name="daddress[da_same_as_hq_address]" id="da_same_as_hq_address" class="input-checkbox checkbox" value="1">
                            <label for="da_same_as_hq_address" class="label">
                                <?= __('Same as Headquarters Address') ?>
                            </label>
                        </div>
                    </div>
                <div class="field daddress-country _required">
                    <label class="label" for="daddress_country">
                        <span><?= $block->escapeHtml(__('Country')) ?></span>
                    </label>
                    <div class="control">
                    <?php $countryBlock = $block->getLayout()->createBlock('Magento\Directory\Block\Data');?>
                    <?= $countryBlock->getCountryHtmlSelect($defValue = "HR", $name = "daddress[daddress_country]", $id = "daddress_country", $title = 'Country');?>
                    </div>
                </div>

        <div class="field daddress-da-street _required">
            <label class="label" for="da_street">
                <span><?= $block->escapeHtml(__('Address')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="daddress[da_street]" id="da_street" value="" title="<?= $block->escapeHtmlAttr(__('Street')) ?>" class="input-text validate-alphanum-with-spaces" data-validate="{required:true}">
            </div>
        </div>


        <div class="field da-city _required">
            <label class="label" for="da_city">
                <span><?= $block->escapeHtml(__('City')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="daddress[da_city]" id="da_city" value="" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="input-text validate-alpha" data-validate="{required:true}">
            </div>
        </div>

         <div class="field daddress-region _required">
            <label class="label" for="region">
                <span><?= $block->escapeHtml(__('Region')) ?></span>
            </label>
            <div class="control">
            <?php 
                $blockObjs = $block->getLayout()->createBlock('Wcb\CustomerRegistration\Block\CustomerRegistration');
                $regions =  $blockObjs->getRegionsOfCountry('HR');         
                $regionLabel = array_column($regions, 'label');
                $regionValue = array_column($regions, 'value');
                $regionArray = array_combine($regionValue, $regionLabel);
                ?>
                <select class="form-control" name="daddress[da_region]" id="da_region">
                    <?php foreach($regionArray as $key => $value){?>                            
                        <option value="<?php echo $key;?>"><?php echo $value ?></option>
                    <?php }?>
                </select>
            </div>
        </div>

        <div class="field daddress-postcode _required">
            <label class="label" for="da_postcode">
                <span><?= $block->escapeHtml(__('Zipcode')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="daddress[da_postcode]" id="da_postcode" value="" title="<?= $block->escapeHtmlAttr(__('Zipcode')) ?>" class="input-text validate-number" data-validate="{required:true}">
            </div>
        </div>
    </div>

     <div class="formSections">

        <legend class="legend"><?php echo __(" Invoice Address")?></legend>
        <div class="field same_as_hq_address">
            <div class="control">
                <input type="checkbox" id="ia_same_as_hq_address" name="iaddress[ia_same_as_hq_address]" class="input-checkbox checkbox" value="1">
                <label for="ia_same_as_hq_address" class="label">
                    <?= __('Same as Headquarters Address') ?>
                </label>
            </div>
        </div>
        <div class="field ia-country _required">
            <label class="label" for="ia_country">
                <span><?= $block->escapeHtml(__('Country')) ?></span>
            </label>
            <div class="control">
            <?php $countryBlock = $block->getLayout()->createBlock('Magento\Directory\Block\Data');?>

            <?= $countryBlock->getCountryHtmlSelect($defValue = "HR", $name = "iaddress[country]", $id = "iaddress[country]", $title = 'Country');?>

            </div>
        </div>

        <div class="field company-street _required">
                        <label class="label" for="ia_street">
                            <span><?= $block->escapeHtml(__('Address')) ?></span>
                        </label>
                        <div class="control">
                            <input type="text" name="iaddress[ia_street]" id="ia_street" title="<?= $block->escapeHtmlAttr(__('Street')) ?>" class="input-text validate-alphanum-with-spaces" data-validate="{required:true}">
                        </div>
                    </div>

        <div class="field iaddress-city _required">
            <label class="label" for="ia_city">
                <span><?= $block->escapeHtml(__('City')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="iaddress[ia_city]" id="ia_city" value="" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="input-text validate-alpha" data-validate="{required:true}">
            </div>
        </div>

        <div class="field iaddress-ia-region _required">
            <label class="label" for="ia_region">
                <span><?= $block->escapeHtml(__('Region')) ?></span>
            </label>
            <div class="control">
            <?php 
                $blockObjs = $block->getLayout()->createBlock('Wcb\CustomerRegistration\Block\CustomerRegistration');
                $regions =  $blockObjs->getRegionsOfCountry('HR');         
                $regionLabel = array_column($regions, 'label');
                $regionValue = array_column($regions, 'value');
                $regionArray = array_combine($regionValue, $regionLabel);
                ?>
                <select class="form-control" name="iaddress[ia_region]" id="ia_region">
                    <?php foreach($regionArray as $key => $value){?>                            
                        <option value="<?php echo $key;?>"><?php echo $value ?></option>
                    <?php }?>
                </select>
            </div>
        </div>

        <div class="field daddress-postcode _required">
            <label class="label" for="ia_postcode">
                <span><?= $block->escapeHtml(__('Zipcode')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="iaddress[ia_postcode]" id="ia_postcode" value="" title="<?= $block->escapeHtmlAttr(__('Zipcode')) ?>" class="input-text validate-number" data-validate="{required:true}">
            </div>
        </div>
    </div>
    <?php
        $helper = $this->helper("Wcb\CustomerRegistration\Helper\Data");
        $enabled = $helper->isNewUserEnabled();
        $sitekey = $helper->getSiteKey();
        $secretkey = $helper->getSecretKey();
        if($enabled){
    ?>
    <div class="form-group required googleCaptcha">
            <div class="g-recaptcha required" id="recaptcha"
                data-sitekey="<?php echo $sitekey;?>">
            </div>
                <div style="display:none" id="error-msg">
                <span><?php echo __('This is a required field.') ?></span>
            </div>
        </div>
<?php

}
?>
    <div class="field choice newsletterAcceptance">
        <label for="is_subscribed" class="label newsletter">
            <input type="checkbox"
                   name="is_subscribed"
                   title="<?= $block->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>"
                   value="1"
                   id="is_subscribed"
                <?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                   class="checkbox"/>
                   <span class="checkmark"> </span>
            
                <span><?= $block->escapeHtml(__('Sign Up for Newsletter')) ?></span>
            </label>
        </div>
            <?php /* Extensions placeholder */ ?>
            <?= $block->getChildHtml('customer.form.register.newsletter') ?>


        <div class="form-group _required ">
            <label for="privacy_policy" class="newsletter">
            <input type="checkbox" id="privacy_policy" name="privacy_policy" value="1" title="<?php echo 'Accept the privacy policy' ?>" class="checkbox required-entry">
            <span class="checkmark"> </span>
            <?php echo 'Accept the privacy policy' ?> (<a href="javascript:void(0)" id="privacy-policy-ex"><?php echo 'privacy policy'; ?></a>)</label>
            </div>
            
    
        <input type="hidden" id="company_email" name="company_email" value="">

        <div class="actions-toolbar">
                <button type="submit" class="action submit primary-button btn160" id="save-button" title="Save"><span><?= $block->
                    escapeHtmlAttr(__('Save')) ?></span>
                </button>
        </div>
        <div id="popup-modal" style="display:none;">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('privacy-login')->toHtml();?>
        </div>

        <div id="popup-modal-signup" style="display:none;">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('privacy-newsletter')->toHtml();?>
        </div>
    </fieldset>
            
    </form>

</div>
    </div>
</div>
<script>
    require([
        'jquery',
        'passwordStrengthIndicator'
    ], function ($) {
        'use strict';

        $("#password").passwordStrengthIndicator({
              "passwordStrengthMeterSelector":"[data-role=strength-meter]",
              "passwordStrengthMeterLabelSelector":"[data-role=strength-meter-label]"
        });
    });

    require(['jquery'],function($) {
        $(document).ready(function () {
            $("#country").prop("disabled", true);
            $('#confirm_email_address').change(function() {
                $('#company_email').val($(this).val());
            });
            $("#company_country").prop("disabled", true);
            $("#daddress_country").prop("disabled", true);
            $("#ia_country").prop("disabled", true);
            var da_ckbox = $('#da_same_as_hq_address');
            var ia_ckbox = $('#ia_same_as_hq_address');
        $('#da_same_as_hq_address').on('click',function () {
            if (da_ckbox.is(':checked')) {
            var hq_region_val = $('#region').find(":selected").val();
            var hq_city_val = $('#city').val();
            var hq_address_val = $('#street').val();
            var hq_zip_val = $('#postcode').val();

                $('#da_region').val(hq_region_val).change();
                $('#da_city').val(hq_city_val);
                $('#da_street').val(hq_address_val);
                $('#da_postcode').val(hq_zip_val);
            } else {
                $('#da_region').val('').change();
                $('#da_city').val('');
                $('#da_street').val('');
                $('#da_postcode').val('');
            }
        });
        $('#ia_same_as_hq_address').on('click',function () {
            if (ia_ckbox.is(':checked')) {
            var hq_region_val = $('#region').find(":selected").val();
            var hq_city_val = $('#city').val();
            var hq_address_val = $('#street').val();
            var hq_zip_val = $('#postcode').val();
                $('#ia_region').val(hq_region_val).change();
                $('#ia_city').val(hq_city_val);
                $('#ia_street').val(hq_address_val);
                $('#ia_postcode').val(hq_zip_val);
            } else {
                $('#ia_region').val('').change();
                $('#ia_city').val('');
                $('#ia_street').val('');
                $('#ia_postcode').val('');
            }
        });
        });
    });
</script>

<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        },
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($, modal) {
            $("#privacy-policy-ex").click(function(e){
                var popup = modal(options, $('#popup-modal'));
                $('#popup-modal').modal('openModal');
            });
            var options = {
                type: 'popup',
                title: '',
                modalClass: 'termsCodition',
                responsive: false,
                innerScroll: true,
                title: 'Privacy Policy',
                modalCloseBtn: false,
                buttons: false
            };
        }
    );
</script>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($, modal) {
            $("#is_subscribed").click(function(e){
                var popup = modal(options, $('#popup-modal-signup'));
                $('#popup-modal-signup').modal('openModal');
            });
            var options = {
                type: 'popup',
                title: '',
                modalClass: 'termsCodition',
                responsive: false,
                innerScroll: true,
                title: 'PRAVILA O PRIVATNOSTI',
                modalCloseBtn: false,
                buttons: [{
                    text: $.mage.__('I accept'),
                    class: 'accept',
                    click: function () {
                      if ($('#is_subscribed').is(
                      ":checked")) {
                    } else {                        
                        $('#is_subscribed').attr('checked', 'checked');
                    }
                        this.closeModal();
                    }
                    
                },
                {
                    text: $.mage.__('I do not accept'),
                    class: 'notAccept',
                    click: function () {
                        if ($('#is_subscribed').is(
                      ":checked")) {
                        $('#is_subscribed').removeAttr('checked');
                    } else {                        
                        $('#is_subscribed').removeAttr('checked');
                    }
                        this.closeModal();
                    }
                    
                }]
            };
        }
    );
</script>
<?php 
    $ajaxurl = $block->getUrl('excustomer/account/verifycompany');
?>
<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function(){
        $('#vat_tax_id').on('change keyup', function () {
            var tax_value = $("#vat_tax_id").val();
            var minlength = 11;
            var customurl = "<?php echo $ajaxurl;?>";
            if (tax_value.length >= minlength && tax_value != '') {
                $.ajax({
                    url: customurl,
                    type: "GET",
                    data: {CompanyOib:tax_value},
                    showLoader: true //use for display loader 
                }).done(function (data) {
                    // if (data.success != null) {
                    //     $('#save-button').prop('disabled', false);
                    // }                
                    if (data.success == 'true') { 
                        alert('gfhgff');
                        $('#save-button').prop('disabled', true);
                        $( "#link-error" ).append( "Company OIB already exists. Please enter valid company OIB." );  // set the message as html of span
                    } 
                    return true;
                });}
            });
        });
    });
</script>
<script>
    function checkCaptcha() {
        if ((jQuery('#g-recaptcha-response').val()) === '') {
            jQuery('#error-msg').css('display', 'block');
            jQuery('#error-msg').css('color', '#df280a');
            jQuery('#error-msg').css('font-size', 16);
            return false;
        }
        else {
            jQuery('#error-msg').css('display', 'none');
        }
    }
</script>