<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="title-actions-links" data-bind="scope: 'requisition.action.edit'">
    <button class="action add" type="button"
            data-bind="
                click: edit.bind($data, {}),
                visible: isCanCreateList()">
        <span><?= $block->escapeHtml(__('Create New Order Template')) ?></span>
    </button>
</div> 
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "requisition.action.edit": {
                        "component": "Magento_RequisitionList/js/requisition/action/edit",
                        "editModuleName": "requisition.edit"
                    },
                    "requisition.edit": {
                        "component": "Magento_RequisitionList/js/requisition/list/edit",
                        "modal": "add_to_requisition_popup",
                        "saveUrl": "<?= $block->escapeUrl($block->getUrl('rest/V1/requisition_lists')) ?>"
                    }
                }
            }
        }
    }
</script>
