<div class="quoteWrapper">
<div class="quoteTitle">
  <div class="columnTitle"><h2>Currently valid offers for: Branch office (30793301) - zagreb</h2></div>
  <div class="columnBut"><div class="myInquiry"> My Inquiry </div></div>
</div>

<section id="elements"> 
   <ol class="collection collection-container">
      <!-- The first list item is the header of the table -->
      <li class="item item-container" >
         <div class="attribute" data-name="Rb. b">Rb. b</div>
         <!-- Enclose semantically similar attributes as a div hierarchy -->
         <div class="attribute" data-name="Offer code">Offer code</div>
         <div class="attribute" data-name="The customer">The customer</div>
         <div class="attribute" data-name="Contact">Contact</div>
         <div class="attribute" data-name="Expires">Expires</div>
         <div class="attribute" data-name="Terms of payment">Terms of payment</div>
         <div class="attribute" data-name="Remark">Remark</div>
         <div class="attribute" data-name="Total sum">Total sum</div>
         <div class="attribute"></div>
      </li>
      <!-- The rest of the items in the list are the actual data -->
      <li class="item item-container" data-role="collapsible">
         <div class="attribute" data-name="Rb. b">1</div>
         <div class="attribute" data-name="Offer code">PPO21-024551</div>
         <div class="attribute" data-name="The customer">Emporium-pj vrhovljan (44910401)</div>
         <div class="attribute" data-name="Contact">26.05.2021</div>
         <div class="attribute" data-name="Expires">02.06.2021</div>
         <div class="attribute" data-name="Terms of payment">30 DANA</div>
         <div class="attribute" data-name="Remark"></div>
         <div class="attribute" data-name="Total sum">233,13 HRK</div>
         <div class="attribute detbutton">
            <div class="details" data-role="trigger"> Details </div>
            <div class="addBasket">Add to basket</div>
         </div>
      </li> 
      <div class="resp-row-three" data-role="content">
         <div class="row-three">
            <ol class="collection collection-container">
               <!-- The first list item is the header of the table -->
               <li class="item item-sub-container" >
                     <div class="attribute"></div>
                     <div class="attribute"></div>
                     <div class="attribute" data-name="Item code">Item code</div>
                     <div class="attribute" data-name="Name">Name</div>
                     <div class="attribute" data-name="Quantity">Quantity</div>
                     <div class="attribute" data-name="VPC">VPC</div>
                     <div class="attribute" data-name="Discount(%)">Discount(%)</div>
                     <div class="attribute" data-name="VPC after discount">VPC after discount</div>
               </li>
               <!-- The rest of the items in the list are the actual data -->
               <li class="item item-sub-container" data-role="collapsible">
                     <div class="attribute">1</div>
                     <div class="attribute">Images</div>
                      <div class="attribute" data-name="Item code">687 171220</div>
                      <div class="attribute" data-name="Name">Set-kvaka i rozeta-eventus-kljuc-l.Zn-cr-POLIR/MAR</div>
                     <div class="attribute" data-name="Quantity">1</div>
                     <div class="attribute" data-name="VPC">233,13 HRK</div>
                     <div class="attribute" data-name="Discount(%)">25.00</div>
                     <div class="attribute" data-name="VPC after discount">174,85 HRK</div>
               </li>
               <li class="item item-sub-container" data-role="collapsible">
                     <div class="attribute">2</div>
                     <div class="attribute">Images</div>
                      <div class="attribute" data-name="Item code">687 171222</div>
                      <div class="attribute" data-name="Name">Rozeta-eventus-kljuc-l.Zn-cr-POLIR/MAR</div>
                     <div class="attribute" data-name="Quantity">10</div>
                     <div class="attribute" data-name="VPC">533,11 HRK</div>
                     <div class="attribute" data-name="Discount(%)">35.00</div>
                     <div class="attribute" data-name="VPC after discount">574,55 HRK</div>
               </li>
               <!-- The rest of the items in the list are the actual data -->
            </ol>
         </div>
      </div>
      <li class="item item-container" data-role="collapsible">
         <div class="attribute" data-name="Rb. b">2</div>
         <div class="attribute" data-name="Offer code">PPO22-024555</div>
         <div class="attribute" data-name="The customer">pj vrhovljan (44910401)</div>
         <div class="attribute" data-name="Contact">26.05.2022</div>
         <div class="attribute" data-name="Expires">02.06.2022</div>
         <div class="attribute" data-name="Terms of payment">20 DANA</div>
         <div class="attribute" data-name="Remark"></div>
         <div class="attribute" data-name="Total sum">333,13 HRK</div>
         <div class="attribute detbutton">
            <div class="details" data-role="trigger"> Details </div>
            <div class="addBasket">Add to basket</div>
         </div>
      </li>
      <div class="resp-row-three" data-role="content">
         <div class="row-three">
         <ol class="collection collection-container">
               <!-- The first list item is the header of the table -->
               <li class="item item-sub-container" >
                     <div class="attribute"></div>
                     <div class="attribute"></div>
                     <div class="attribute" data-name="Item code">Item code</div>
                     <div class="attribute" data-name="Name">Name</div>
                     <div class="attribute" data-name="Quantity">Quantity</div>
                     <div class="attribute" data-name="VPC">VPC</div>
                     <div class="attribute" data-name="Discount(%)">Discount(%)</div>
                     <div class="attribute" data-name="VPC after discount">VPC after discount</div>
               </li>
               <!-- The rest of the items in the list are the actual data -->
               <li class="item item-sub-container" data-role="collapsible">
                     <div class="attribute">1</div>
                     <div class="attribute">Images</div>
                      <div class="attribute" data-name="Item code">687 171220</div>
                      <div class="attribute" data-name="Name">Set-kvaka i rozeta-eventus-kljuc-l.Zn-cr-POLIR/MAR</div>
                     <div class="attribute" data-name="Quantity">1</div>
                     <div class="attribute" data-name="VPC">233,13 HRK</div>
                     <div class="attribute" data-name="Discount(%)">25.00</div>
                     <div class="attribute" data-name="VPC after discount">174,85 HRK</div>
               </li>
               <li class="item item-sub-container" data-role="collapsible">
                     <div class="attribute">2</div>
                     <div class="attribute">Images</div>
                      <div class="attribute" data-name="Item code">687 171222</div>
                      <div class="attribute" data-name="Name">Rozeta-eventus-kljuc-l.Zn-cr-POLIR/MAR</div>
                     <div class="attribute" data-name="Quantity">10</div>
                     <div class="attribute" data-name="VPC">533,11 HRK</div>
                     <div class="attribute" data-name="Discount(%)">35.00</div>
                     <div class="attribute" data-name="VPC after discount">574,55 HRK</div>
               </li>
               <li class="item item-sub-container" data-role="collapsible">
                     <div class="attribute">3</div>
                     <div class="attribute">Images</div>
                      <div class="attribute" data-name="Item code">687 171233</div>
                      <div class="attribute" data-name="Name">Eventus-kljuc-l.Zn-cr-POLIR/MAR</div>
                     <div class="attribute" data-name="Quantity">30</div>
                     <div class="attribute" data-name="VPC">333,11 HRK</div>
                     <div class="attribute" data-name="Discount(%)">55.00</div>
                     <div class="attribute" data-name="VPC after discount">374,55 HRK</div>
               </li>
               <!-- The rest of the items in the list are the actual data -->
            </ol>
         </div>
      </div>
   </ol>
</section>
</div>

<script>
   require([
       'jquery',
       'accordion'], function ($) {
         $("#elements").accordion({
       multipleCollapsible: true,
       collapsible: true,
       active: false,
       animate: {
           duration: 400
       }
   });
   });

</script>
