<?php $quoteCollection = $block->getNegotiableQuoteCollection(); ?>
<?php if ($quoteCollection->count() > 0) { ?>
    <div class="my-inquiry">
        <div class="quoteTitle">
            <div class="columnTitle"><h2><?= __("My Inquiry") ?></h2></div>
        </div>

        <section id="elements">
            <ol class="collection collection-container">
                <li class="item item-container">
                    <div class="attribute" data-name="Inquiry ID"><?= __("Inquiry ID") ?></div>
                    <div class="attribute" data-name="Date of Inquiry"><?= __("Date of Inquiry") ?></div>
                    <div class="attribute" data-name="Comment of Inquiry"><?= __("Comment") ?></div>
                    <div class="attribute" data-name="Action"><?= __("Action") ?></div>
                </li>
                <?php foreach ($quoteCollection as $requestQuote) { ?>
                    <li class="item item-container" data-role="collapsible">
                        <div class="attribute" data-name="Inquiry ID"><?= $requestQuote->getParentId() ?></div>
                        <div class="attribute"
                             data-name="Date of Inquiry"><?= $block->getDateFormat($requestQuote->getCreatedAt()) ?></div>
                        <div class="attribute" data-name="Comment of Inquiry"><?= $requestQuote->getComment() ?></div>
                        <div class="attribute">
                            <div class="details" data-role="trigger"><?= __("Details") ?></div>
                        </div>
                    </li>
                    <div class="resp-row-three" data-role="content">
                        <div class="row-three">
                            <ol class="collection collection-container">
                                <li class="item item-sub-container">
                                    <div class="attribute" data-name="Item Image">Item Image</div>
                                    <div class="attribute" data-name="Item No">Item No</div>
                                    <div class="attribute" data-name="Item Name">Item Name</div>
                                    <div class="attribute" data-name="Quantity">Quantity</div>
                                    <div class="attribute" data-name="Date">Date</div>
                                </li>
                                <?php $_items = $block->getQuoteCollectionById($requestQuote->getParentId())->getAllVisibleItems(); ?>
                                <?php foreach ($_items as $item) { ?>
                                    <li class="item item-sub-container" data-role="collapsible">
                                        <div class="attribute" data-name="Item Image">
                                            <img src="<?= $block->getItemImage($item) ?>">
                                        </div>
                                        <div class="attribute"
                                             data-name="Item No"><?= $item->getProduct()->getProductCode() ?></div>
                                        <div class="attribute" data-name="Item Name"><?= __($item->getName()) ?></div>
                                        <div class="attribute" data-name="Quantity"><?= $item->getQty() ?></div>
                                        <div class="attribute"
                                             data-name="Date"><?= $block->getDateFormat($item->getCreatedAt()) ?></div>
                                    </li>
                                <?php } ?>
                            </ol>
                        </div>
                    </div>
                <?php } ?>
            </ol>
        </section>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
    <script>
        require([
            'jquery',
            'accordion'], function ($) {
            $("#elements").accordion({
                multipleCollapsible: true,
                collapsible: true,
                active: false,
                animate: {
                    duration: 400
                }
            });
        });
    </script>
<?php } else { ?>
    <div class="message info empty">
        <div><?= __("We can't find request quote matching the selection.") ?></div>
    </div>
<?php } ?>
