<?php
   /**
    * Copyright © Magento, Inc. All rights reserved.
    * See COPYING.txt for license details.
    */

   // phpcs:disable Magento2.Templates.ThisInTemplate
   // phpcs:disable Magento2.Files.LineLength.MaxExceeded

   /** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

   $_item = $block->getItem();
   $product = $_item->getProduct();
   $isVisibleProduct = $product->isVisibleInSiteVisibility();
   /** @var \Magento\Msrp\Helper\Data $helper */
   $helper = $this->helper(Magento\Msrp\Helper\Data::class);
   $canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
   $shippingProductHelper = $helper = $this->helper(Wurth\Shippingproduct\Helper\Data::class);
   $shippingProductCode = $shippingProductHelper->getShippingProductCode();
   $removeHelper = $this->helper(Magento\Checkout\Helper\Cart::class);
  // login check helper
   $logedIn=$this->helper("Wcb\Component\Helper\Data")->isLoggedIn();
   $checkoutHelper = $this->helper("Wcb\Checkout\Helper\Data");
   $product = $checkoutHelper->getLoadProduct($product->getId());

   $type = '';
  $displayUnitQty = 1;
  $minimumAndMeasureQty = '';
   if ($product->getBaseUnitOfMeasureId()) {
       $type = $checkoutHelper->getType($product->getBaseUnitOfMeasureId());
       $displayUnitQty = $checkoutHelper->getQuantityUnitByQuantity($block->getQty(), $product);
       $minimumAndMeasureQty = $checkoutHelper->getMinimumAndMeasureQty($product);
   }

  /*  var_dump($product->getMinimumSalesUnitQuantity());
    var_dump($product->getBaseUnitOfMeasureId());
    var_dump($product->getProductUnitOfMeasureCode());
    exit;*/
  ?>
<tbody class="cart item">
   <tr class="item-info table__row">
      <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="colitem" >
         <?php if ($block->hasProductUrl()) :?>
         <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
            title="<?= $block->escapeHtml($block->getProductName()) ?>"
            tabindex="-1"
            class="product-item-photos">
         <?php else :?>
         <span class="product-item-photos">
         <?php endif;?>
         <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
         <?php if ($block->hasProductUrl()) :?>
         </a>
         <?php else :?>
         </span>
         <?php endif; ?>
         <div class="product-item-details">
            <strong class="item-no"><?= $product->getProductCode() ?></strong>
            <strong class="product-item-name">
            <?php if ($block->hasProductUrl()) :?>
            <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
            <?php else :?>
            <?= $block->escapeHtml($block->getProductName()) ?>
            <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()) :?>
            <dl class="item-options">
               <?php foreach ($_options as $_option) :?>
               <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
               <dt><?= $block->escapeHtml($_option['label']) ?></dt>
               <dd>
                  <?php if (isset($_formatedOptionValue['full_view'])) :?>
                  <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                  <?php else :?>
                  <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                  <?php endif; ?>
               </dd>
               <?php endforeach; ?>
            </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()) :?>
            <?php foreach ($messages as $message) :?>
            <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
               <div><?= $block->escapeHtml($message['text']) ?></div>
            </div>
            <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
         </div>
      </td>
      <td class="colqty data-name" data-th="<?= $block->escapeHtml(__('Qty')) ?>" data-name="<?= $block->escapeHtml(__('Quantity x pieces = total quantity')) ?>">
          <?php if ($shippingProductCode != $_item->getSku()) { ?>
              <div class="productFieldset">
                    <div class="qty-field-wrapper">
                       <div id="<?= /* @escapeNotVerified */
                          $_item->getId() ?>-dec" class="decreaseQty icon-interface-minus" data-item-id="<?= /* @escapeNotVerified */
                       $_item->getId() ?>">
                       </div>
                       <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                          name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                          data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                          <!--value="--><?/*= $block->escapeHtmlAttr($block->getQty()) */?>"
                          value="<?= $block->escapeHtmlAttr($displayUnitQty) ?>"
                          type="number"
                          size="4"
                          step="any"
                          title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                          class="input-text qty cart-item-qty-box"
                          data-validate="{required:true,'validate-greater-than-zero':true}"
                          data-role="cart-item-qty"
                              data-item-id="<?= /* @escapeNotVerified */ $_item->getId() ?>"/>
                       <div id="<?= /* @escapeNotVerified */
                          $_item->getId() ?>-upt" class="increaseQty icon-interface-plus" data-item-id="<?= /* @escapeNotVerified */
                       $_item->getId() ?>"></div>
                    </div>

                <div class="cpCount">
                   <select>
                      <option> <?= $minimumAndMeasureQty ?> PC</option>
                   </select>
                </div>
                <div class="cpCount">
                   <select>
                      <option><?= $block->getQty() ?></option>
                   </select>
                </div>

         </div>
         <div class="imd-avilable">
         <?php if ($logedIn) { ?>
            <span class="imd-van"><img src=" <?php echo $block->getViewFileUrl('Magento_Checkout::images/Rectangle434.png'); ?>" /></span>
            <span class="imd-cart"><img src=" <?php echo $block->getViewFileUrl('Magento_Checkout::images/cartico.png'); ?>" /></span>
            <span class="imd-day">12-14</span>
            <span class="imd-avlb">The quantity will be available for the displayed number of days</span>
            <?php } ?>
         </div>
          <?php } ?>
      </td>
      <td colspan="2">
          <?php if ($shippingProductCode != $_item->getSku()) { ?>
         <table>
            <tr  class="seprator">
               <td class="data-name" data-name="<?= $block->escapeHtml(__('Jed. measure')) ?>"> <span class="carmrp" ><?= $type ?></span> </td>
               <td class="data-name" data-name="<?= $block->escapeHtml(__('Price type')) ?>"> <span class="imd-cart"><img src=" <?php echo $block->getViewFileUrl('Magento_Checkout::images/star-red.png'); ?>" /></span> </td>
            </tr>
         </table>
          <?php } ?>
      </td>
      <td colspan="2">
         <table>
            <tr>
               <td class="data-name" data-name="<?= $block->escapeHtml(__('Price')) ?>">
                  <div class="colsubtotal">
                     <?php if ($logedIn) { ?>
                     <div class="cpdis"><span class="cpcross">145,66 HRK </span> <span class="cpper"> (-25%)</span></div>
                     <span class="cpgprice">1816.17</span>
                     <?php } else { ?>
                        <span class="cpgprice">Login to view price</span>
                        <?php } ?>
                  </div>
               </td>
               <td class="data-name" data-name="<?= $block->escapeHtml(__('Amount without VAT')) ?>">
               <?php if ($logedIn) { ?>
                 <span class="carmrp">2,401.88</span>
                        <?php } ?>
               </td>
            </tr>
         </table>
      </td>
      <td class="toolDel" colspan="1">
          <?php if ($shippingProductCode != $_item->getSku()) { ?>
              <span class="dIcon remove-cart-item" data-item-id="<?= $_item->getId(); ?>">
                  <img src=" <?php echo $block->getViewFileUrl('Magento_Checkout::images/deleteico.png'); ?>" />
              </span>
          <?php } ?>
      </td>
   </tr>
</tbody>
