<?php
   /**
    * Copyright © Magento, Inc. All rights reserved.
    * See COPYING.txt for license details.
    */

   // phpcs:disable Magento2.Templates.ThisInTemplate
   // phpcs:disable Magento2.Files.LineLength.MaxExceeded

   /** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

   $_item = $block->getItem();
   $product = $_item->getProduct();
   $isVisibleProduct = $product->isVisibleInSiteVisibility();
   /** @var \Magento\Msrp\Helper\Data $helper */
   $helper = $this->helper(Magento\Msrp\Helper\Data::class);
   $canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
   $shippingProductHelper = $helper = $this->helper(Wurth\Shippingproduct\Helper\Data::class);
   $shippingProductCode = $shippingProductHelper->getShippingProductCode();
   $removeHelper = $this->helper(Magento\Checkout\Helper\Cart::class);
   ?>
<tbody class="cart item">
   <tr class="item-info table__row">
      <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="colitem" >
         <?php if ($block->hasProductUrl()) :?>
         <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
            title="<?= $block->escapeHtml($block->getProductName()) ?>"
            tabindex="-1"
            class="product-item-photos">
         <?php else :?>
         <span class="product-item-photos">
         <?php endif;?>
         <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
         <?php if ($block->hasProductUrl()) :?>
         </a>
         <?php else :?>
         </span>
         <?php endif; ?>
         <div class="product-item-details">
            <strong class="item-no">250</strong>
            <strong class="product-item-name">
            <?php if ($block->hasProductUrl()) :?>
            <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
            <?php else :?>
            <?= $block->escapeHtml($block->getProductName()) ?>
            <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()) :?>
            <dl class="item-options">
               <?php foreach ($_options as $_option) :?>
               <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
               <dt><?= $block->escapeHtml($_option['label']) ?></dt>
               <dd>
                  <?php if (isset($_formatedOptionValue['full_view'])) :?>
                  <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                  <?php else :?>
                  <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                  <?php endif; ?>
               </dd>
               <?php endforeach; ?>
            </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()) :?>
            <?php foreach ($messages as $message) :?>
            <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
               <div><?= $block->escapeHtml($message['text']) ?></div>
            </div>
            <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
         </div>
      </td> 
      <td class="colqty data-name" data-th="<?= $block->escapeHtml(__('Qty')) ?>" data-name="<?= $block->escapeHtml(__('Quantity x pieces = total quantity')) ?>">
         <div class="productFieldset">
            <div class="qty-field-wrapper">
               <div id="<?= /* @escapeNotVerified */
                  $_item->getId() ?>-dec" class="decreaseQty icon-interface-minus">
               </div>
               <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                  name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                  data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                  value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                  type="number"
                  size="4"
                  step="any"
                  title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                  class="input-text qty"
                  data-validate="{required:true,'validate-greater-than-zero':true}"
                  data-role="cart-item-qty"/>
               <div id="<?= /* @escapeNotVerified */
                  $_item->getId() ?>-upt" class="increaseQty icon-interface-plus"></div>
            </div>
            <div class="cpCount">
               <select>
                  <option> 120 PC</option>
                  <option> 120 PC</option>
                  <option> 120 PC</option>
                  <option> 120 PC</option>
               </select>
            </div>
            <div class="cpCount">
               <select>
                  <option> 100 </option>
                  <option> 100 </option>
                  <option> 100 </option>
                  <option> 100 </option>
               </select>
            </div>
         </div>
         <div class="imd-avilable">
            <span class="imd-van"><img src=" <?php echo $block->getViewFileUrl('Magento_Checkout::images/Rectangle434.png'); ?>" /></span>
            <span class="imd-cart"><img src=" <?php echo $block->getViewFileUrl('Magento_Checkout::images/cartico.png'); ?>" /></span>
            <span class="imd-day">12-14</span>
            <span class="imd-avlb">The quantity will be available for the displayed number of days</span>
         </div>
      </td>
      <td colspan="2">
         <table>
            <tr  class="seprator">
               <td class="data-name" data-name="<?= $block->escapeHtml(__('Jed. measure')) ?>"> <span class="carmrp" >KOM</span> </td>
               <td class="data-name" data-name="<?= $block->escapeHtml(__('Price type')) ?>"> <span class="imd-cart"><img src=" <?php echo $block->getViewFileUrl('Magento_Checkout::images/star-red.png'); ?>" /></span> </td>
            </tr>
         </table>
      </td>
      <td colspan="2">
         <table>
            <tr>
               <td class="data-name" data-name="<?= $block->escapeHtml(__('Price')) ?>">
                  <div class="colsubtotal">
                     <div class="cpdis"><span class="cpcross">145,66 HRK </span> <span class="cpper"> (-25%)</span></div>
                     <span class="cpgprice">1816.17</span>
                  </div>
               </td>
               <td class="data-name" data-name="<?= $block->escapeHtml(__('Amount without VAT')) ?>">
                  <span class="carmrp">2,401.88</span>
               </td>
            </tr>
         </table>
      </td>
      <td class="toolDel" colspan="1">
          <?php if ($shippingProductCode != $_item->getSku()) { ?>
              <a href="#"
                 title="<?= $block->escapeHtml(__('Remove item')) ?>"
                 class="action action-delete"
                 data-post='<?= /* @noEscape */ $removeHelper->getDeletePostJson($_item) ?>'>
                  <span class="dIcon">
                      <img src=" <?php echo $block->getViewFileUrl('Magento_Checkout::images/deleteico.png'); ?>" />
                  </span>
              </a>

          <?php } ?>
      </td>
   </tr>
</tbody>
<script type="text/javascript">
   require(["jquery"],function($){
       $('#<?php echo $_item->getId();?>-upt, #<?php echo $_item->getId();?>-dec').on("click",function(){
           var $this = $(this);
           var ctrl = ($(this).attr('id').replace('-upt','')).replace('-dec','');
           var currentQty = $("#cart-"+ctrl+"-qty").val();
           if($this.hasClass('increaseQty')){
               var newAdd = parseInt(currentQty)+parseInt(1);
                $("#cart-"+ctrl+"-qty").val(newAdd);
           }else{
                if(currentQty>1){
                   var newAdd = parseInt(currentQty)-parseInt(1);
                   $("#cart-"+ctrl+"-qty").val(newAdd);
                }
           }
       });
   });
</script>
<script type="text/javascript">
   require(["jquery"], function ($) {
       $('.increaseQty, .decreaseQty').on("click", function () {
           let inputElem = $(this).parents('td').find('input');
           let currentQty = inputElem.val();
           if ($(this).hasClass('increaseQty')) {
               inputElem.val(parseInt(currentQty) + parseInt(1));
           } else {
               if (currentQty > 1) {
                   inputElem.val(parseInt(currentQty) - parseInt(1));
               }
           }
           // $("#form-validate").submit();
       });
   });
</script>
