<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Msrp\Helper\Data;

/** @var $block Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$shippingProductHelper = $this->helper(Wurth\Shippingproduct\Helper\Data::class);
$shippingProductCode = $shippingProductHelper->getShippingProductCode();
$removeHelper = $this->helper(Magento\Checkout\Helper\Cart::class);
$checkoutHelper = $this->helper("Wcb\Checkout\Helper\Data");
$product = $checkoutHelper->getLoadProduct($product->getId());
$stockApiData = $checkoutHelper->getStockApiData($product->getProductCode(), $block->getQty());
$priceApiData = $checkoutHelper->getPriceApiData($product->getProductCode());

$type = '';
$displayUnitQty = 1;
$minimumAndMeasureQty = '';
if ($product->getBaseUnitOfMeasureId()) {
    $type = $checkoutHelper->getType($product->getBaseUnitOfMeasureId());
    $displayUnitQty = $checkoutHelper->getQuantityUnitByQuantity($block->getQty(), $product);
    $minimumAndMeasureQty = $checkoutHelper->getMinimumAndMeasureQty($product);
}

// login check helper

$logedIn = $this->helper("Wcb\Component\Helper\Data")->isLoggedIn();
?>
<tbody class="cart item">
<tr class="item-info table__row">
    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="colitem">
        <?php if ($block->hasProductUrl()) : ?>
        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
           title="<?= $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photos">
            <?php else : ?>
            <span class="product-item-photos">
         <?php endif; ?>
         <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
         <?php if ($block->hasProductUrl()) : ?>
        </a>
    <?php else : ?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="item-no"><?= $product->getProductCode() ?></strong>
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) : ?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else : ?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()) : ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                            <?php else : ?>
                                <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()) : ?>
                <?php foreach ($messages as $message) : ?>
                    <div class="cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) : ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
        </div>
    </td>
    <td class="colqty data-name" data-th="<?= $block->escapeHtml(__('Qty')) ?>"
        data-name="<?= $block->escapeHtml(__('Quantity x pieces = total quantity')) ?>">
        <?php if ($shippingProductCode != $_item->getSku()) { ?>
            <div class="productFieldset">
                <div class="qty-field-wrapper">
                    <div id="<?= /* @escapeNotVerified */
                    $_item->getId() ?>-dec" class="decreaseQty icon-interface-minus"
                         data-item-id="<?= /* @escapeNotVerified */
                         $_item->getId() ?>">
                    </div>
                    <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                           name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                           value="<?= $block->escapeHtmlAttr($displayUnitQty) ?>"
                           type="number"
                           size="4"
                           step="any"
                           title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                           class="input-text qty cart-item-qty-box"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"
                           data-item-id="<?= /* @escapeNotVerified */
                           $_item->getId() ?>"/>
                    <div id="<?= /* @escapeNotVerified */
                    $_item->getId() ?>-upt" class="increaseQty icon-interface-plus"
                         data-item-id="<?= /* @escapeNotVerified */
                         $_item->getId() ?>"></div>
                </div>

                <div class="cpCount">
                     <?= $minimumAndMeasureQty ?> PC
                </div>
                <div class="cpCount">
                   <?= $block->getQty() ?>
                </div>

            </div>
            <div class="imd-avilable">
                <?php if ($logedIn) { ?>
                    <span class="wcb-logged-remove">
                         <?php if (isset($stockApiData['color'])) { ?>
                             <span class="imd-van">
                                    <img
                                        src="<?php echo $block->getViewFileUrl('images/stock/' . $stockApiData['color'] . '.svg'); ?>"/>
                            </span>
                         <?php } ?>
                        <?php if (isset($stockApiData['showDisplayDays'])) { ?>
                            <span class="imd-cart">
                                <img
                                    src="<?php echo $block->getViewFileUrl('images/stock/van-' . $stockApiData['color'] . '.svg'); ?>"/>
                            </span>
                        <?php } ?>
                        <?php if (isset($stockApiData['showDisplayDays'])) { ?>
                            <span
                                class="imd-day"><?= isset($stockApiData['stockDays']) ? $stockApiData['stockDays'] : '' ?></span>
                            <span
                                class="imd-avlb">The quantity will be available for the displayed number of days</span>
                        <?php } ?>

                      </span>
                <?php } ?>
            </div>
        <?php } ?>
    </td>
    <td colspan="2">
        <?php if ($shippingProductCode != $_item->getSku()) { ?>
            <table>
                <tr class="seprator">
                    <td class="data-name" data-name="<?= $block->escapeHtml(__('Jed. measure')) ?>"><span
                            class="carmrp"><?= $type ?></span></td>
                    <td class="data-name no-display" data-name="<?= $block->escapeHtml(__('Price type')) ?>">
                        <span class="imd-cart">
                            <?php if (isset($priceApiData['discount']) && $priceApiData['discount'] != 0) { ?>
                                <img
                                    src=" <?php echo $block->getViewFileUrl('Magento_Checkout::images/star-red.png'); ?>"/>
                            <?php } ?>
                        </span>
                    </td>
                </tr>
            </table>
        <?php } ?>
    </td>
    <td colspan="2">
        <table>
            <tr>
                <td class="data-name" data-name="<?= $block->escapeHtml(__('Price')) ?>">
                    <div class="colsubtotal">
                        <?php if ($logedIn) { ?>
                            <span class="wcb-logged-remove">
                              <?php if (isset($priceApiData['discount']) &&
                                  isset($priceApiData['price']) &&
                                  $priceApiData['discount'] != 0) { ?>
                                  <div class="cpdis">
                                     <span
                                         class="cpcross"><?= $checkoutHelper->getFormattedPrice($priceApiData['price']) ?> </span>
                                     <span class="cpper"> (- <?= $priceApiData['discount'] ?>%)</span>
                                 </div>
                                  <span class="cpgprice">
                                     <?= $checkoutHelper->getFormattedPrice($priceApiData['discount_price']) ?>
                                 </span>
                              <?php } else { ?>
                                  <?php if (isset($priceApiData['price'])) { ?>
                                      <span class="cpgprice">
                                     <?= $checkoutHelper->getFormattedPrice($priceApiData['price']) ?>
                                 </span>
                                  <?php }
                              } ?>
                          </span>
                        <?php } ?>
                        <?php if (!$logedIn) { ?>
                        <span class="wcb-not-logged">
                                    <span class="cpgprice">Login to view price</span>
                              <span>
                          <?php } ?>
                    </div>
                </td>
                <td class="data-name" data-name="<?= $block->escapeHtml(__('Amount without VAT')) ?>">
                    <?php if ($logedIn) { ?>
                        <span class="wcb-logged-remove">
                     <span class="carmrp">
                         <?php if ($canApplyMsrp) : ?>
                             <span class="cart msrp subtotal">--</span>
                         <?php else : ?>
                             <?= $block->getRowTotalHtml($_item) ?>
                         <?php endif; ?>
                     </span>
                   </span>
                    <?php } ?>
                </td>
            </tr>
        </table>
    </td>
    <td class="toolDel" colspan="1">
        <?php if ($shippingProductCode != $_item->getSku()) { ?>
            <span class="dIcon remove-cart-item" data-item-id="<?= $_item->getId(); ?>">
                  <img src=" <?php echo $block->getViewFileUrl('Magento_Checkout::images/deleteico.png'); ?>"/>
              </span>
        <?php } ?>
    </td>
</tr>
</tbody>
