<?php $loggedIn = $this->helper("Wcb\Component\Helper\Data")->isLoggedIn(); ?>
<?php if ($loggedIn) { ?>
    <?php $checkoutHelper = $this->helper("Wcb\Checkout\Helper\Data"); ?>
    <div class="cart-summary-terms">
        <p>
            <input class="forcheck" id="accept_terms" type="checkbox" checked>
            <label for="accept_terms">
        <span class="formtemrs"
              data-bind="i18n: 'I accept the terms of sale through the online store (General terms)'"></span>
            </label>
        </p>
    </div>
<?php } ?>
