<div class="cart-summary-terms">
    <span class="cart-notice" data-bind="i18n: 'For all orders 300 HRK (excluding VAT) we charge delivery in the amount of 20 HRK + VAT'"></span>

    <input class="forcheck" id="accept_terms" type="checkbox" checked>
    <label for="accept_terms">
        <span class="formtemrs" data-bind="i18n: 'I accept the terms of sale through the online store (General terms)'"></span>
    </label>
</div>
