
<div class="tab">
  <button class="tablinks mob-tabs menu-tab" data-cityname="menu-tab"  id="defaultOpen">Menu</button>
  <button class="tablinks mob-tabs accounts " data-cityname="accounts" >Account</button>
  
</div>


<?php
	$items = $block->getItemsActive();
	$itemsActive = json_decode($items); 
	$htmlLink = array();
	
 if(count($itemsActive)):
 ?>
		<nav id="menu-tab" class="nav-container visible-lg visible-md tabcontent">
			
				<div class="mobile-menu">
			
				
						<div id="pt_custommenu" class="pt_custommenu">
						<?php
						
						$showhome = $block->getConfig('is_home');	
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
						//var_dump($request); die('111');
						$active = '';
						if ($request->getFullActionName() == 'cms_index_index') {
							$active = ' act';
						}
						$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');

						$base_url = $urlInterface->getBaseUrl();
						if($showhome){
							$id     = "_home";
							$html[] = '<div id="pt_menu' . $id . '" class="pt_menu' . $active . '">';
							$html[] = '<div class="parentMenu">';
							$html[] = '<a href="'.$base_url.'">';
							$html[] = '<span>'.__('Home').'</span>';
							$html[] = '</a>';
							$html[] = '</div>';
							$html[] = '</div>';
							$html = implode("\n", $html);
							echo $html;
						}
			
							$item = 0;
				
							$id = null; 
							$label = null; 
							foreach($itemsActive as $itemActive) { 
									$item++;
									$item1 =  explode( '_', $itemActive ) ;
									$label = $item1[0]; 
									$id = $item1[1];
									 switch ($label) {
										case "cms":							
												echo $block->CmsLink($id,'desktop'); 
											break;
										case "block":			
												echo $block->CustomLink($id,'desktop');
											break;
										case "category":									
												echo $block->drawCustomMenuItemMob($id,0,false,$item);											
											break;
										}
							
					
								?>
								
								
								
								<?php	
																												

							}
								?>						
						<div class="clearBoth"></div>
					</div>	
				</div>
		</nav>

	<div id="accounts" class="tabcontent" data-bind="scope: 'customer'">
			<!-- ko if: customer().firstname  -->
			<ul>
				<li><span  data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1', '%1')) ?>').replace('%1', customer().firstname)"></span>!</li>	
				<li> <a href="<?php echo $block->getUrl("customer/account"); ?>"><!-- ko i18n: 'My Acoount' --><!-- /ko --> </a></li> 
				<li><a href="<?php echo $block->getUrl('customer/account/logout'); ?>"><!-- ko i18n: 'Logout' --><!-- /ko --></a></li> 		
			</ul>
			<!-- /ko -->

		<!-- ko ifnot: customer().firstname  -->
			<ul>
				<li> <a href="<?php echo $block->getUrl("customer/account/login"); ?>"> <!-- ko i18n: 'Login / Registration' --><!-- /ko --></a></li> 
			</ul>
		<!-- /ko -->
    </div>
		

		<script type="text/javascript">
		//<![CDATA[
			var CUSTOMMENU_POPUP_EFFECT = 0;
			var CUSTOMMENU_POPUP_TOP_OFFSET = 64;
		//]]>
		</script>

    <script>
        requirejs(['jquery', 'mobilemenu'], function($) {           
        });
    </script>

<?php endif ?>

