<?php
	$items = $block->getItemsActive();
	$itemsActive = json_decode($items); 
	$htmlLink = array();
 if(count($itemsActive)):
 ?>
		<nav class="nav-container visible-lg visible-md">
			
				<div class="">
			
				
						<div id="pt_custommenu" class="pt_custommenu">
						<?php
						
						$showhome = $block->getConfig('is_home');	
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
						//var_dump($request); die('111');
						$active = '';
						if ($request->getFullActionName() == 'cms_index_index') {
							$active = ' act';
						}
						$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');

						$base_url = $urlInterface->getBaseUrl();
						if($showhome){
							$id     = "_home";
							$html[] = '<div id="pt_menu' . $id . '" class="pt_menu' . $active . '">';
							$html[] = '<div class="parentMenu">';
							$html[] = '<a href="'.$base_url.'">';
							$html[] = '<span>'.__('Home').'</span>';
							$html[] = '</a>';
							$html[] = '</div>';
							$html[] = '</div>';
							$html = implode("\n", $html);
							echo $html;
						}
			
							$item = 0;
				
							$id = null; 
							$label = null; 
							foreach($itemsActive as $itemActive) { 
									$item++;
									$item1 =  explode( '_', $itemActive ) ;
									$label = $item1[0]; 
									$id = $item1[1];
									 switch ($label) {
										case "cms":							
												echo $block->CmsLink($id,'desktop'); 
											break;
										case "block":			
												echo $block->CustomLink($id,'desktop');
											break;
										case "category":									
												echo $block->drawCustomMenuItem($id,0,false,$item);											
											break;
										}
							
					
								?>
								
								
								
								<?php																						

							}
								?>	
								<div class="Cflag-wrap">	
									<span class="Cflag"><img src=" <?php echo $block->getViewFileUrl('Wcb_Megamenu::images/flag.png'); ?>" /></span>
									<span>Croatia</span>

								</div>				
						<div class="clearBoth"></div>
					</div>
					
					
						
					
				</div>
				
		</nav>
		<script type="text/javascript">
			
		</script>

		 <script>
        requirejs(['jquery', 'wcbmegamenu'], function($) {           
        });
    </script>

		<script type="text/javascript">
		//<![CDATA[
			var CUSTOMMENU_POPUP_EFFECT = 2;
			var CUSTOMMENU_POPUP_TOP_OFFSET = 64;
		//]]>
		</script>
<?php endif ?>

