<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="col-md social-block">
<?php if(!empty($block->getStoresArray())): ?>
    <div class="wcbstore-wrapper" id="wcbstore-div" data-bind="scope:'wcbstore'">
<!-- ko template: getTemplate() --><!-- /ko -->
<script type="text/x-magento-init">
    {
        "#wcbstore-div": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "wcbstore": {
                        "component": "Wcb_Store/js/wcbstore",
                        "config": {
                                 "template" : "Wcb_Store/wcbstore",
                                 "stores_option" : <?php echo json_encode($block->getStoresArray()); ?>
                                }

                    }
                }
            }
        }
    }
</script>
</div>
<?php endif; ?>
</div>

