<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 */
$fieldNameFile = \Magento\AdvancedCheckout\Model\Import::FIELD_NAME_SOURCE_FILE;
$fieldImportedFlagFile = \Magento\AdvancedCheckout\Helper\Data::REQUEST_PARAMETER_SKU_FILE_IMPORTED_FLAG;
$extErrorText = __(
    'The file could not be uploaded because it is in the wrong format. Please select a CSV file to upload.'
);
?>
<div class="field upload skus choose-excel">
    <div class="control" data-mage-init='{"fieldsetControls": {}, "fileChooser": {
            "fileNameSelector": "[name=<?= $block->escapeJs($fieldNameFile) ?>]",
            "fileNameIndicatorSelector": "[name=<?= $block->escapeJs($fieldImportedFlagFile) ?>]"
            },
            "quickOrderFile":{
            "fileNameSelector": "[name=<?= $block->escapeJs($fieldNameFile) ?>]",
            "extErrorText": "<?= $block->escapeHtml($extErrorText) ?>",
            "urlSku":"<?= $block->escapeUrl($block->getUrl('quickorder/ajax/search')) ?>"
            }}'>

            <div class="upload-container">
            <div class="file-upload"><?= $block->escapeHtml(__('Choose File')) ?></div>
            <input id="customer_sku_csv" type="file" data-reset="true" class="action-upload" name="<?= $block->escapeHtmlAttr($fieldNameFile) ?>">
        </div>

        <div class="note">
            <p>
                <?= $block->escapeHtml(__('File must be in .csv format and include "SKU" and "QTY" columns')); ?>
                <?= $block->getChildHtml('quick_order_download_template_link') ?>
            </p>
        </div>
        <div class="form-cart-button">
            <button id="add_to_cart_upload" class="add-to-basket" disabled><?= $block->escapeHtml(__('Add to Basket')) ?></button>
        </div>
        <div class="success-import no-display">
            <div class="message success">
                <div class="success-import-message">
                    <span class="success-import-count">5</span>
                    <?= __('Products you can add in your cart.') ?>
                </div>
            </div>
        </div>
        <div class="error-import no-display">
            <div class="message error">
                <div class="success-import-message">
                    <span class="error-import-count">2</span>
                    <?= __('Products you can not add in your cart.') ?>
                </div>
            </div>
            <table class="error-import-product" border="1">
                <tr>
                    <th><?= __("Product Code") ?></th>
                    <th><?= __("Qty") ?></th>
                    <th><?= __("Error") ?></th>
                </tr>
            </table>
        </div>
    </div>
</div>
