<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>

<?php if ($_orders && count($_orders)) : ?>   
    <?php if ($block->getPagerHtml()) : ?>
    <div class="mt-5">
        <div class="col-md-3  text-contaner">
                <div class="input-box"> <input type="text" class="form-control" id="searchInput"> <i class="fa fa-search"></i> </div>  
        </div>
    
        <div class="col-md top-pager-contaner">
             <div class="order-products-toolbar toolbar bottom top-pager"><?= $block->getPagerHtml() ?></div>
      </div>
    </div>
        
    <?php endif ?>
    <div class="table-wrapper order-items order-detail">
    <table id="wcb-data-table" class="table table-striped table-bordered nowrap" style="width:100%">
        <thead class="wcb-first-row">
            <tr>
                <th class="name">Rb</th>
                <th data-orderable="false">Status</th>
                <th class="position">Name</th>
                <th>Date</th>
                <th>Online shop number</th>
                <th>Internal order code</th>
                <th>ERP Number</th>
                <th>Follow Order</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php  foreach ($_orders as $_order) : ?>
           <tr>
                <td data-th="RB">1.</td>
                <td data-th="Status"><span class="green-box"></span></td>
                <td data-th="Name">Kristian Koenig</td>
                <td data-th="Date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                <td data-th="Online shop number">15986</td>
                <td data-th="Internal order code"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                <td data-th="ERP Number">PP20-0119803</td>
                <td data-th="Follow Order" ><?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Follow Order')) ?></span>
                                </a>
                            <?php endif ?></td>
                <td data-th="<?= $block->escapeHtml(__('Follow Order')) ?>"><a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>">Details</a></td>
            </tr>

        <?php endforeach; ?>
          
        </tbody>
    </table>
 </div>

<?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom bottom-pager"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>

<script>
    require(['jquery.dataTables.min'],function($) {
    $(window).load(function () {
        // alert('load from external jquery');
    });});
</script>



