<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>

<!--<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra) : ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?> -->

<?php if ($_orders && count($_orders)) : ?>   
    <?php if ($block->getPagerHtml()) : ?>
    <div class="mt-5">
        <div class="col-md-3  text-contaner">
                <div class="input-box"> <input type="text" class="form-control" id="searchInput"> <i class="fa fa-search"></i> </div>  
        </div>
    
        <div class="col-md top-pager-contaner">
             <div class="order-products-toolbar toolbar bottom top-pager"><?= $block->getPagerHtml() ?></div>
      </div>
    </div>
        
    <?php endif ?>
<div class="tracking-order-table">
<div id="elements"> 
   <ol class="collection collection-container" id="filter">
      <li class="item item-container" >
         <div class="attribute" data-name="Rb">Rb <span class="down-arrow"></span></div>
         <div class="attribute" data-name="Status">Status <span class="group-arrow"></span></div>
         <div class="attribute" data-name="Name">Name <span class="group-arrow"></span></div>
         <div class="attribute" data-name="Date">Date <span class="group-arrow"></span></div> 
         <div class="attribute" data-name="Online shop number">Online shop number <span class="group-arrow"></span></div>
         <div class="attribute" data-name="Internal order code">Internal order code <span class="group-arrow"></span></div>
         <div class="attribute" data-name="ERP Number">ERP Number <span class="group-arrow"></span></div> 
         <div class="attribute" data-name="Follow Order">Follow Order <span class="group-arrow"></span></div> 
         <div class="attribute"></div>           
      </li>
      <?php  foreach ($_orders as $_order) : ?>
      <li class="item item-container" data-role="collapsible">
         <div class="attribute" data-name="<?= $block->escapeHtml(__('Rb')) ?>">1.</div>
         <div class="attribute" data-name="<?= $block->escapeHtml(__('Status')) ?>"><span class="green-box"></span></div>
         <div class="attribute" data-name="<?= $block->escapeHtml(__('Name')) ?>">Kristian Koenig</div>
         <div class="attribute" data-name="<?= $block->escapeHtml(__('Date')) ?>"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></div>
         <div class="attribute" data-name="<?= $block->escapeHtml(__('Online shop number')) ?>">15986</div>
         <div class="attribute" data-name="<?= $block->escapeHtml(__('Internal order code')) ?>"><?= $block->escapeHtml($_order->getRealOrderId()) ?></div>
         <div class="attribute" data-name="<?= $block->escapeHtml(__('ERP Number')) ?>">PP20-0119803</div>
         <div class="attribute follow-order" data-name="<?= $block->escapeHtml(__('Follow Order')) ?>"><?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Follow Order')) ?></span>
                                </a>
                            <?php endif ?></div>
         <div class="attribute details-botton" ><a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>">Details</a></div>
      </li> 
      <?php endforeach; ?>
     
     
   </ol>
 </div>
</div>
<?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom bottom-pager"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>

<script>
 require(['jquery', 'jquery/ui'], function($){ 
     $('#searchInput').keyup(function(){
    var searchText = $(this).val();
  
    $('ol > li').each(function(){
        var currentLiText = $(this).text(),
            showCurrentLi = currentLiText.indexOf(searchText) !== -1;        
            $(this).toggle(showCurrentLi);
        
    });     
});
 });
</script>


