<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info myProfile">
    <div class="block-content">
    <div class="container">
  <div class="row">
    <div class="col-md addBox">
    <p><span class="textBold"><?= $block->escapeHtml($block->getName()) ?></span> </p>                              

    <p><span class="textBold">Broj korisnika:</span> 2380 </p>
   <p><span class="textBold">Customer code:</span> <span class="redText"> 30799331 </span> (Kristian Koening) </p>
   <p><span class="textBold">Email:</span> <span><?= $block->escapeHtml($block->getCustomer()->getEmail()) ?> </span> (<span class="textBlue"><a href="!#">Change</a></span>)</p>
   <div id = "changePass" onclick = "displayLoginBox()">Change Password</div>
        <div id = "passBox" style="display:none;"> 
        <form>
  <div class="form-group">
    <label class="inputLevel">Current Password <span>*</span> </label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">    
  </div>
  <div class="form-group">
    <label class="inputLevel">New Password <span>*</span></label>
    <input type="password" class="form-control" id="newpassword">
    <small id="emailHelp" class="form-text text-muted">Password Strength: No Password</small>
  </div>
  <div class="form-group">
    <label class="inputLevel">Confirm New Password <span>*</span></label>
    <input type="password" class="form-control" id="confirmpassword">    
  </div>
  <div class="form-group">
  <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>
              
        </div>
    </div>

    <div class="col-md addBox">
    <div class="boxTitle">
                <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
   </div>
    <?php if ($block->isNewsletterEnabled()): ?>
                    <div class="newslettertext">
                        <?php if ($block->getIsSubscribed()): ?>
                            <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>"> <?= $block->escapeHtml(__('You already sign up to our Newsletter')) ?> </a>
                            
                        <?php else: ?>
                            <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>"> <?= $block->escapeHtml(__('I want to sign up for the Newsletter')) ?></a>
                        <?php endif; ?>
                    </div>
        <?php endif; ?>
    </div>
    <div class="col-md addBox">
        <div class="boxTitle">
                <span><?= $block->escapeHtml(__('Sales representtative contact details')) ?></span>
        </div>
            <p><span class="textBold">Name: </span>Damir Pavlovic</p>
            <div class="emailBox"><span class="icon-wuerth-e-mail"> </span> Email: damir.pavlovic@gmail.com </div>
    </div>
  </div>
</div>
<div class="seprator"></div>
<div class="container last">
    <div class="row">
        <div class="col-md-3 addBoxs">
        <div class="boxTitle"> Contact Center </div>
            <p class="textBold">Würth-Hrvatska doo ,</p>
            <p>Franje Lučića 32, 10 090 , Zagreb</p>
            <p><span class="icon-com-phone-a"></span> Tel: +385 (01) 3498-784 </p>
            <p><span class="cil-fax icon-doc-print"></span> Fax: +385 (01) 3498-783</p>  
            <p class="emailCom"><span class="icon-wuerth-e-mail"> </span> <b>Email: </b> wuerth@wuerth.com.hr </p>      

        </div>
        <div class="col-md-9">
        <div class="boxTitle"> Welcome to contact center WÜRTH-HRVATSKA DOO</div>
        <p class="textBluebold">Working hours contact center mon-fri: 8:00 - 16:00</p> 
        <div class="row"> 
            <div class="col-md-4"> 
               <div class="supportBox">
                   <div class="supportIcon"><img src="<?php echo $this->getViewFileUrl('Magento_Customer::images/consult-1.svg'); ?>"></div>
                   <div class="phoneDetails">
                       <p class="redColor">08004260</p>
                       <p class="genText">Sales, support and information</p>
                  </div>
                </div>   
            </div>
            <div class="col-md-4"> 
               <div class="supportBox">
                   <div class="supportIcon"> <img src="<?php echo $this->getViewFileUrl('Magento_Customer::images/consult-2.svg'); ?>"> </div>
                   <div class="phoneDetails">
                       <p class="redColor">08004260</p>
                       <p class="genText">Complaints, service and shipment status</p>
                  </div>
                </div>   
            </div>
            <div class="col-md-4"> 
               <div class="supportBox">
                   <div class="supportIcon"> <img src="<?php echo $this->getViewFileUrl('Magento_Customer::images/consult-3.svg'); ?>"> </div>
                   <div class="phoneDetails">
                       <p class="redColor">08004260</p>
                       <p class="genText">Complaints, service and shipment status</p>
                  </div>
                </div>   
            </div>
        </div>
    </div>
    
</div>
    </div>                    

        
        <?php //echo $block->getChildHtml('additional_blocks'); ?>
    </div>
</div>
<script type="text/javascript">
require(['jquery'], function($) {
$('#changePass').on('click', function(e){
$("#passBox").toggle();
});
$('.block.block-dashboard-addresses').css('display','none');
$('.block.block-dashboard-orders').css('display','none');
});
 </script> 