<?php

use Wcb\BestSeller\Block\AbstractSlider;
use Magento\Framework\App\Action\Action;

/** @var AbstractSlider $block */
$helper = $this->helper(\Wcb\BestSeller\Helper\Data::class);
$mode = 'grid';
$type = 'widget-product-grid';
$title = $block->getTitle();
$blockId = $block->getSliderId() . uniqid('-', false);
$categoryitems = $block->getProductCollection()['category'];
$items = $block->getProductCollection()['product'];

$offer = $block->getOffer();

$moduleName = $this->getRequest()->getModuleName();
$controllerName = $this->getRequest()->getControllerName();
$actionName = $this->getRequest()->getActionName();
$pageIdentifier = $moduleName.'_'.$controllerName .'_'.$actionName;
?>
<?php
if($pageIdentifier == 'cms_index_index') {
?>
<div class="carousel-wrap container-inner nowOffer">
	<h2><?php echo __('Now offer on')?></h2>    
    <div class="yourAction"><?php echo __('Your actions in June')?></div>
	<div class="owl-theme owl-carouselrp">
		<?php foreach($categoryitems as $category){ ?>
			<div class="item">
                    <div class="product-grid">
                        <div class="product-image">
                            <a href="#" class="image">
                                <img class="img-1" src="http://m2.wc.b2b.com/static/version1641270815/frontend/wc/b2b_eshop/hr_HR/Magento_Catalog/images/product/placeholder/small_image.jpg">
                            </a>
                           
                        </div>
                        <div class="product-content">
                            <div class="productName"><a href="#">ZASTITNE RUKAVICE ZA MONTAZU</a></div>
                            <div class="onlineoff">Cijena za online kupovinu</div>
                        <div class="price">
                            <span class="cpgprice">149, <sup>99</sup></span> 
                            <span class="cpcross">199,<sup>99</sup> </span></div>
                        </div>
                    </div>
		</div>
    	<?php } ?> 
	</div>
</div>
<?php } ?>
<script type="text/javascript">
          /**
 * Created By : Rohan Hapani
 */
require(['jquery', 'owlcarousel'], function($) {
    $(document).ready(function() {
        $('.owl-carouselrp').owlCarousel({
            loop: true,
            margin: 30,
            nav: true,
            navText: [
                "<i class='icon-interface-left'></i>",
                "<i class='icon-interface-right'></i>"
            ],
            autoplay: true,
            autoplayHoverPause: true,
            responsive: {
                0: {
                  items: 1
                },
                600: {
                  items: 3
                },
                1000: {
                  items: 4
                }
            }
        });
        $('.owl-carouselrp').trigger('refresh.owl.carousel');
        window.dispatchEvent(new Event('resize'));
    });
});
        </script>

<?php
if($pageIdentifier == 'cms_index_index') {
?>
<section class="bestSellerWrap container-inner">
<h2><?php echo __("Best Sellers in Protupozarna zastita"); ?></h2>
<?php
if ($block->getHelperData()->isEnabled() && $items && $items->getSize()): ?>
    <div class="block-content mp-product-slider-content">
        <div class="bestSeller products-<?php echo /** @noEscape */  $mode ?> <?php echo /** @noEscape */  $mode ?>">
            <ol class="product-items widget-viewed-grid">
                <?php $iterator = 1; ?>
                <div id="mp-list-items-<?php echo /** @noEscape */ $blockId ?>" class="owl-carousel owl-theme">
                    <?php foreach ($items as $_item): ?>
                        <?php echo ($iterator++ == 1) ? '<div class="item">' : '</div><div class="item">' ?>
                        <div class="slider-product-item-info">
                            <a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product photo slider-product-item-photo">
                                <?php echo $block->getImage($_item, 'recently_viewed_products_grid_content_widget')->toHtml(); ?>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>  
                                <?php echo /** @noEscape */ $block->getProductDetailsHtml($_item) ?>                                                    
                              
                            </div>
                            
                            <div class="price-off"> <?php echo $offer ?></div> 
                        </div>
                        <?php echo ($iterator === count($items) + 1) ? '</div>' : '' ?>
                    <?php endforeach ?>
                </div>
            </ol>
        </div>
        <script type="text/javascript">
            require([
                'jquery'
            ], function ($) {
                var lazyLoad = <?php echo /** @noEscape */ $helper->getModuleConfig('slider_design')['lazyLoad']?>;
                if (lazyLoad === 1) {
                    $('.slider-product-item-info .photo .product-image-photo').each(function (){
                        var el = $(this);
                        el.addClass('owl-lazy');
                        el.attr('data-src',el.attr('src'));
                    })
                }
            });
        </script>
        <?php echo $block->getPagerHtml() ?>
    </div>
    <script>
        require(['jquery', 'owlcarousel'], function ($) {
            $('#mp-list-items-<?php echo /** @noEscape */ $blockId ?>').owlCarousel(<?php echo /** @noEscape */ $block->getAllOptions()?>);
            $(".custom-bpslider").insertBefore(".page-footer");
        });
    </script>
<?php endif; ?>
    </section>
<?php } elseif($pageIdentifier == "checkout_cart_index"){
echo $this->getLayout()->createBlock("Wcb\BestSeller\Block\BestSellerProducts")->setTemplate("Wcb_BestSeller::recommanded-products.phtml")->toHtml();
} ?>