<?php

use Wcb\BestSeller\Block\AbstractSlider;
use Magento\Framework\App\Action\Action;

/** @var AbstractSlider $block */
$helper = $this->helper(\Wcb\BestSeller\Helper\Data::class);
$mode = 'grid';
$type = 'widget-product-grid';
$title = $block->getTitle();
$blockId = $block->getSliderId() . uniqid('-', false);
$items = $block->getProductCollection();
if ($block->getHelperData()->isEnabled() && $items && $items->getSize()): ?>
    <div class="block-content mp-product-slider-content">
        <div class="products-<?php echo /** @noEscape */  $mode ?> <?php echo /** @noEscape */  $mode ?>">
            <ol class="product-items widget-viewed-grid">
                <?php $iterator = 1; ?>
                <div id="mp-list-items-<?php echo /** @noEscape */ $blockId ?>" class="owl-carousel owl-theme">
                    <?php foreach ($items as $_item): ?>
                        <?php echo ($iterator++ == 1) ? '<li class="product-item product-slider"">' : '</li><li class="product-item product-slider"">' ?>
                        <div class="slider-product-item-info">
                            <a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product photo slider-product-item-photo">
                                <?php echo $block->getImage($_item, 'recently_viewed_products_grid_content_widget')->toHtml(); ?>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>

                                <?php if ($block->canShowReview()): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, 'short', true) ?>
                                <?php endif; ?>

                                <?php echo /** @noEscape */ $block->getProductDetailsHtml($_item) ?>

                                <?php if ($block->canShowPrice()): ?>
                                    <?php echo /** @noEscape */ $block->getProductPriceHtml($_item, $type) ?>
                                <?php endif; ?>

                                <div class="product actions slider-product-item-actions product-item-actions">
                                    <?php if ($block->canShowAddToCart()): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <form data-role="tocart-form" data-product-sku="<?php echo $block->escapeHtml($_item->getSku()) ?>" action="<?php echo /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php echo /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?php echo /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?php echo /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?php echo /** @noEscape */ __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php echo $block->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php echo $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div class="secondary-addto-links actions-secondary"
                                             data-role="add-to-links">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   data-post='<?php echo /** @noEscape */ $block->getAddToWishlistParams($_item); ?>'
                                                   class="action towishlist" data-action="add-to-wishlist"
                                                   title="<?php echo /** @noEscape */ __('Add to Wish List') ?>">
                                                    <span><?php echo /** @noEscape */ __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl()): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare"
                                                   data-post='<?php echo /** @noEscape */ $compareHelper->getPostDataParams($_item); ?>'
                                                   data-role="add-to-links"
                                                   title="<?php echo /** @noEscape */ __('Add to Compare') ?>">
                                                    <span><?php echo /** @noEscape */ __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php echo ($iterator === count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </div>
            </ol>
        </div>
        <script type="text/javascript">
            require([
                'jquery'
            ], function ($) {
                var lazyLoad = <?php echo /** @noEscape */ $helper->getModuleConfig('slider_design')['lazyLoad']?>;
                if (lazyLoad === 1) {
                    $('.slider-product-item-info .photo .product-image-photo').each(function (){
                        var el = $(this);
                        el.addClass('owl-lazy');
                        el.attr('data-src',el.attr('src'));
                    })
                }
            });
        </script>
        <?php echo $block->getPagerHtml() ?>
    </div>
    <script>
        require(['jquery', 'mageplaza/core/owl.carousel'], function ($) {
            $('#mp-list-items-<?php echo /** @noEscape */ $blockId ?>').owlCarousel(<?php echo /** @noEscape */ $block->getAllOptions()?>);
        });
    </script>
<?php endif; ?>

