<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $_outputHelper = $block->getData('outputHelper');

$objectmanager = \Magento\Framework\App\ObjectManager::getInstance();


?>

<!-- For Category -->
<?php $level = $block->getLayer()->getCurrentCategory()->getLevel(); ?>
<?php //die($level);?>
<?php $ProductCount = $block->getLayer()->getCurrentCategory()->getProductCollection()->Count(); ?>
<?php $catId = $block->getLayer()->getCurrentCategory()->getId(); ?>
<?php $catName = $block->getLayer()->getCurrentCategory()->getName(); ?>
<?php $currentCat = $block->getLayer()->getCurrentCategory(); ?>
<?php $level5Collection =  $currentCat->getProductCollection()->addAttributeToSelect('*'); ?> 
<?php $firstProduct =  $level5Collection->getFirstItem(); ?>
<?php $firstProductExtraRow = $block->getExtraAttributeData($firstProduct); ?>
<?php $subcategories = []; ?>
<?php $subcategories = $block->getCategoryChildrenData($catId);
//   echo "<pre>";
//         print_r($subcategories->getData());
//       //  print_r($subcategories->getData());
//         exit;
?>
<!-- End For Category -->
<!-- For Product -->
<?php
$viewMode = 'grid';
$pid= [];
$extraRow = "";
$imageDisplayArea = 'category_page_grid';
$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$pos = $block->getPositioned();
$product=false;
?>
 <?php 
      // login check helper
   $logedIn=$this->helper("Wcb\Component\Helper\Data")->isLoggedIn();
  ?>
<!-- <div data-mage-init='{"plp":{}}' ></div> -->
<!-- End For Product -->
<?php if( $level <  5 ) { ?>

   <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>

    <div class="products wrapper grid products-grid">
        <ol class="products list items product-items productListingwrapper">
            <?php foreach ($subcategories as $subcategory): ?>
                <?php $productCount = $subcategory->getProductCollection()->getSize(); ?>
                <?php $subcategory = $block->getCategoryData($subcategory->getId()); ?>
                <?php //$subcategory->hasChildren() ?>
                <?php if ($productCount > 1): ?>
                    <li class="item product product-item">
                        <div class="product-item-info">
                            <?php if ($_imgUrl = $subcategory->getImageUrl()): ?>
                                <a href="<?= $subcategory->getUrl() ?>" class="product photo product-item-photo">
            <span class="product-image-container">
            <?php $_imgHtml = '<img src="' . $_imgUrl . '" />'; ?>
            <?php echo $_imgHtml = $_outputHelper->categoryAttribute($subcategory, $_imgHtml, 'image'); ?>
            </span>
                                </a>
                            <?php endif; ?>
                            <div class="product details product-item-details">
                                <a href="<?= $subcategory->getUrl() ?>" class="product photo product-item-photo">
            <span class="product-image-container">
            <?php $_imgHtml = '<img src="' . $_imgUrl . '" />'; ?>
            <?php echo $_imgHtml = $_outputHelper->categoryAttribute($subcategory, $_imgHtml, 'image'); ?>
            </span>
                                </a>
                                <strong class="product name product-item-name PlpItemName">
                                    <a class="product-item-link"
                                       href="<?= $subcategory->getUrl() ?>"><?= $subcategory->getName() ?></a>
                                </strong>
                          </div>
                        </div>
                    </li>
                <?php endif; ?>
               <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
<?php } ?>

