<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $_outputHelper = $block->getData('outputHelper');

$objectmanager = \Magento\Framework\App\ObjectManager::getInstance();


?>
<!-- For Category -->
<?php $level = $block->getLayer()->getCurrentCategory()->getLevel(); ?>

<?php //die($level);?>
<?php $ProductCount = $block->getLayer()->getCurrentCategory()->getProductCollection()->Count(); ?>
<?php $catId = $block->getLayer()->getCurrentCategory()->getId(); ?>
<?php $catName = $block->getLayer()->getCurrentCategory()->getName(); ?>
<?php $currentCat = $block->getLayer()->getCurrentCategory(); ?>
<?php $level5Collection =  $currentCat->getProductCollection()->addAttributeToSelect('*'); ?>
<?php $firstProduct =  $level5Collection->getFirstItem(); ?>
<?php $firstProductExtraRow = $block->getExtraAttributeData($firstProduct); ?>
<?php $subcategories = []; ?>
<?php $subcategories = $block->getCategoryChildrenData($catId); ?>
<!-- End For Category -->
<!-- For Product -->
<?php
$viewMode = 'grid';
$kk = "912 814185";
$pid= [];
$extraRow = "";
$imageDisplayArea = 'category_page_grid';
$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$pos = $block->getPositioned();
$product=false;
?>
 <?php
    // login check helper
    $logedIn=$this->helper("Wcb\Component\Helper\Data")->isLoggedIn();
  ?>
<!-- <div data-mage-init='{"plp":{}}' ></div> -->
<!-- End For Product -->
<?php if( $level == 5 ) { ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>

    <div class="products wrapper grid products-grid">
        <ol class="products list items product-items productListingwrapper">
            <?php foreach ($subcategories as $subcategory): ?>
                <?php $productCount = $subcategory->getProductCollection()->getSize(); ?>
                <?php $subcategory = $block->getCategoryData($subcategory->getId()); ?>
                <?php //$subcategory->hasChildren() ?>
                <?php if ($productCount > 1): ?>
                    <li class="item product product-item">
                        <div class="product-item-info">
                            <?php if ($_imgUrl = $subcategory->getImageUrl()): ?>
                                <a href="<?= $subcategory->getUrl() ?>" class="product photo product-item-photo">
            <span class="product-image-container">
            <?php $_imgHtml = '<img src="' . $_imgUrl . '" />'; ?>
            <?php echo $_imgHtml = $_outputHelper->categoryAttribute($subcategory, $_imgHtml, 'image'); ?>
            </span>
                                </a>
                            <?php endif; ?>
                            <div class="product details product-item-details">
                                <a href="<?= $subcategory->getUrl() ?>" class="product photo product-item-photo">
            <span class="product-image-container">
            <?php $_imgHtml = '<img src="' . $_imgUrl . '" />'; ?>
            <?php echo $_imgHtml = $_outputHelper->categoryAttribute($subcategory, $_imgHtml, 'image'); ?>
            </span>
                                </a>
                                <strong class="product name product-item-name PlpItemName">
                                    <a class="product-item-link"
                                       href="<?= $subcategory->getUrl() ?>"><?= $subcategory->getName() ?></a>
                                </strong>
                                <?php if ($level > 4 && $productCount > 1) { ?>
                                  <?php if($logedIn) { ?>
                                    <p class="price-box">
                                        <label>
                                            <span class="startFrom">Start from </span></span><span class="price">1,816.17 HRK</span>
                                    </p>
                                    <p class="view-stock"><a href="#" class="view-stock"><?php echo __("Please select single product to
                                            view stock"); ?> </a></p>
                                     <?php } else { ?>
                                      <span class="view-price"> <?php echo __("Login to view price"); ?> </span>
                                      <?php } ?>
                                    <p class="variation-box <?= (($logedIn ?'logdIn':'notLog')); ?>"><label><?php echo $productCount; ?>
                                            variations </label>
                                    </p>
                                    <p class="variation-buttom"><label><a href="<?= $subcategory->getUrl() ?>"> <?php echo  __("Show variations"); ?> </a></label></p>
                                <?php } ?>
                                <?php if ($level > 4 && $productCount == 1) { ?>
                                    <p class="quantity-available">Quantity available immediately: 90</p>
                                    <p class="price-box"><span class="price">1,816.17 HRK</span></p>
                                    <p class="variation-box"><label> -120 + 100 pc</label></p>
                                    <p class="variation-buttom"><label> Dodaju Kosaricu</label></p>
                                    <p>Count <?php echo $subcategory->getProductCollection()->getSize();; ?></p>
                                <?php } ?>
                            </div>
                        </div>
                    </li>
                <?php endif; ?>
                <?php if (!$subcategory->hasChildren() &&  $productCount == 1): ?>
                    <?php

                       $products = $subcategory->getProductCollection()->addAttributeToSelect('*');

                    ?>
                    <?php foreach ($products as $_product): ?>


                        <?php  $ProductCode = $_product->getProductCode(); ?>

                        <?php $product = true; ?>
                        <li class="item product product-item">
                            <div class="product-item-info"
                                 id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                                 data-container="product-<?= /* @noEscape */ $viewMode ?>">
                                <?php if($ProductCode){ ?>
                                <?php $pid[ $_product->getSku()][] = $ProductCode; ?>
                                <?php $pid[ $_product->getSku()][] = '1'; ?>
                                <?php } ?>

                                <?php
                                $productImage = $block->getImage($_product, $imageDisplayArea);
                                if ($pos != null) {
                                    $position = 'left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;';
                                }

                                ?>
                                <?php // Product Image
                                $product = $objectmanager ->create('Magento\Catalog\Model\Product')->load($_product->getId());
                                $abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct');
                                $productimages = $product->getMediaGalleryImages();

                                ?>
                                <a href="<?= $escaper->escapeUrl($subcategory->getUrl()); ?>"
                                   class="product photo product-item-photo"
                                   tabindex="-1">
                                    <?php
                                    foreach($productimages as $productimage)
                                    {
                                        echo "<img src = ".$productimage['url']. " />";
                                        break;
                                    } ?>
                                </a>
                                <div class="product details product-item-details">
                                    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                    <strong class="product name product-item-name PlpItemName">
                                        <a class="product-item-link"
                                           href="<?= $escaper->escapeUrl($subcategory->getUrl()) ?>">
                                            <?php echo $product->getName(); ?>
                                        </a>
                                    </strong>
                                    <?php if($logedIn) { ?>
                                    <?php $ProductCode = str_replace(' ', '', $ProductCode); ?>

                                    <div id="price_soap<?php echo $ProductCode; ?>" style="display:none;" class="price-box">
                                            <!-- <span>Price:&nbsp;</span>
                                            <span class="price" id="suggestedPriceAsTxtP<?php echo $ProductCode; ?>"></span>
                                            <span class="price" >-</span>
                                            <span class="price" id="suggestedDiscountAsTxtP<?php echo $ProductCode; ?>"></span>
                                            <span class="price" >%</span>
                                            <span class="price" >&nbsp;=&nbsp;</span>-->
                                            <span class="price" id="suggestedSalesPriceInclDiscAsTxtP<?php echo $ProductCode; ?>"></span>
                                            <span class="price" >&nbsp;HRK&nbsp;</span>
                                            <span class="wcb-contaner-group">
                                                <div class="tooltip box redBox">
                                                    <span class="tooltiptext">The item is not available immediately</span>
                                                </div>
                                                <div class="tooltip van redVan">
                                                    <span class="tooltiptext">The quantity will be available for the displayed number of days</span>
                                                </div>
                                                <span class="delivery-time">12 -14</span>
                                            </span>
                                            

                                    </div>

                                    <div><span id="price_loader<?php echo $ProductCode; ?>" class="priceDisplay"><img src="<?=$block->getViewFileUrl('images/loader-h2.gif');?>"/></span></div>




                                    <span class="stock" id="stock_<?php echo $ProductCode; ?>"> </span>
                                      <?php } else { ?>
                                        <span class="view-price"> <?php echo __("Login to view price"); ?> </span>
                                        <?php } ?>
                                    <div class="product-item-inner <?= (($logedIn ?'logdIn':'notLog')); ?>">
                                        <div class="product actions product-item-actions">
                                            <div class="actions-primary">
                                                <?php if ($_product->isSaleable()):?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form"
                                                          data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                          action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                          method="post">
                                                        <input type="hidden"
                                                               name="product"
                                                               value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                        <input type="hidden"
                                                               name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                               value="<?=
                                                               /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                               ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <!--  --------------- -->
                                                        <div class="box-tocart">
                                                            <div class="fieldset productFieldset">
                                                                <div class="field qty">
                                                                    <!-- <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                                                                    //echo __('Qty') ?></span></label> -->
                                                                    <div class="control-qty-cart">
                                                                        <span class=" icon-interface-minus quantity-controls quantity-minus"></span>
                                                                        <input type="number" name="qty" id="qty" maxlength="12" value="1" title="<?php /* @escapeNotVerified */
                                                                        echo __('Qty') ?>" class="qty-default input-text qty"
                                                                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                                                        />
                                                                        <span class="quantity-controls quantity-plus icon-interface-plus"></span>

                                                                    </div>

                                                                </div>
                                                                <div class="pkgCount">
                                                                    <select>
                                                                        <option> 100 PC</option>
                                                                        <option> 100 PC</option>
                                                                        <option> 100 PC</option>
                                                                        <option> 100 PC</option>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <!--  --------------- -->
                                                        <div class="product-actions">
                                                <button type="submit"
                                                        title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary variation-buttom"
                                                        disabled>
                                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                                <div data-role="add-to-links" class="actions-secondary">
                                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                          </form>
                                                <?php else:?>
                                                    <?php if ($_product->isAvailable()):?>
                                                        <div class="stock available">
                                                            <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                                        </div>
                                                    <?php else:?>
                                                        <div class="stock unavailable">
                                                            <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled() && $product): ?>
        <script type="text/x-magento-init">
   {
       "[data-role=tocart-form], .form.map.checkout": {
           "catalogAddToCart": {
               "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
           }

       }
   }
</script>
<?php $pid_json = json_encode($pid) ?>
<?php //echo $pid_json ?>
    <script>
        require(['plp'], function(pdp) {
            pdp.GetMultiProductPrice('<?php echo $pid_json ?>');
            pdp.GetMultiProductStock('<?php echo $pid_json ?>');
        });
    </script>
    <?php endif; ?>
    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            $('.quantity-plus').click(function () {
                var currentQTY = parseInt($(this).parent().parent().find(".qty-default").val());
                currentQTY = currentQTY + 1;
                $(this).parent().parent().find(".qty-default").val(currentQTY);
            });

            $('.quantity-minus').click(function () {
                var currentQTY = parseInt($(this).parent().parent().find(".qty-default").val());
                currentQTY = currentQTY - 1;
                if (currentQTY > 0) {
                    $(this).parent().parent().find(".qty-default").val(currentQTY);
                }
            });
        });
    </script>

<?php } ?>
