<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
/** @var \Magento\Catalog\Helper\Output $_helper */
$_outputHelper = $block->getData('outputHelper');
?>
<?php $level = $block->getLayer()->getCurrentCategory()->getLevel(); ?>
<?php $ProductCount = $block->getLayer()->getCurrentCategory()->getProductCollection()->Count(); ?>
<?php $catId = $block->getLayer()->getCurrentCategory()->getId(); ?>
<?php $subcategories = [] ;?>
<?php $subcategories = $block->getCategoryChildrenData($catId); ?>

<?= $block->getToolbarHtml() ?>
<?= $block->getAdditionalHtml() ?>
<div class="products wrapper grid products-grid">
        <ol class="products list items product-items">
            <?php foreach($subcategories as $subcategory): ?>
                <?php  $productCount = $subcategory->getProductCollection()->Count(); ?>
                <?php $subcategory = $block->getCategoryData($subcategory->getId()); ?>
                <?php if($subcategory): ?>
                <li class="item product product-item">
                    <div class="product-item-info">
                        <?php if ($_imgUrl = $subcategory->getImageUrl()): ?>
                            <a href="<?= $subcategory->getUrl() ?>" class="product photo product-item-photo">
                                <span class="product-image-container">
                                    <?php $_imgHtml = '<img src="' . $_imgUrl . '" />'; ?>
                                    <?php echo $_imgHtml = $_outputHelper->categoryAttribute($subcategory, $_imgHtml, 'image'); ?>
                                </span>
                            </a>
                        <?php endif; ?>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link" href="<?= $subcategory->getUrl() ?>"><?= $subcategory->getName() ?></a>
                            </strong>
                            <?php if($level > 3 && $productCount > 1) { ?>
                                <p class="price-box"><label>Start From </span><span class="price">1,816.17 HRK</span></p>
                             <p class="view-stock"><a href="#" class="view-stock">Please select single product to view stock</a></p>
                            <p class ="variation-box"><label ><?php echo $productCount ; ?> variations</label></p>
                            <p class ="variation-buttom"><label > Show variations</label></p>
                            <?php }  ?>
                            <?php if($level > 3 && $productCount <= 1) { ?>
                                <p class="quantity-available">Quantity available immediately: 90</p>
                            <p class="price-box"><span class="price">1,816.17 HRK</span></p>
                            <p class ="variation-box"><label > -120 + 100 pc</label> </p>
                            <p class ="variation-buttom"><label > Dodaju Kosaricu</label></p>
                            <?php }  ?>

                        </div>
                    </div>
                </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
    </div>

<?= $block->getToolbarHtml() ?>

<?php //endif ?>


