<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>

<?php $_product = $block->getProduct(); ?>
<?php $productCode = $_product->getProductCode(); ?>

<div>
<div class="priceDisplay">Price :   2,421.56 - 25% = 1,816.17 HRK/COM <span class="redStar"></span> </div> 

    <div><span id="price_pdp"><img src="<?= $block->getViewFileUrl('images/loader-h2.gif'); ?>"/></span><span id="price_format" style="display:none;">&nbsp;KN</span></div>
   
</div>
<script type="text/x-magento-init">
    
        {
            "body" : {
                    "pdp": {
                            "pid": "<?php echo $productCode; ?>"
                    }
            }
        }
</script>