<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /** @var \Magento\Catalog\Block\Product\View $block */?>
 
<?php $_product = $block->getProduct();?>
<?php $productCode = $_product->getProductCode();?>

<div>
<span class="wcb-logged">
  <span class="">
<div id="price_soap" style="display:none;" class="priceDisplay">
        <span>Price:&nbsp;</span>
        <span id="suggestedPriceAsTxtP"></span>
        <span>-</span>
        <span id="suggestedDiscountAsTxtP"></span>
        <span>%</span>
        <span>&nbsp;=&nbsp;</span>
        <span id="suggestedSalesPriceInclDiscAsTxtP"></span>
        <span>&nbsp;HRK/COM&nbsp;</span>
        <span class="redStar"></span>
</div>

<div><span id="price_loader" class="priceDisplay"><img src="<?=$block->getViewFileUrl('images/loader-h2.gif');?>"/></span></div>

</span>
<span class="wcb-not-logged">
         <span class="view-price priceDisplay"> <?php echo __("Login to view price"); ?> </span>
</span>

</div>
<script>
require(['pdp'], function(pdp) {
               pdp.soapPrice("<?php echo $productCode ?>");
            });
</script>



