<div class="ios-overview">
      <div class="sales-title"> 
         <?php echo __("IOS detail Kristian koenig (900453)"); ?> 
      </div>

      <table class="table-content">
         <tr>
            <td>Limit:</td>
            <td>9.00</td>
         </tr>
         <tr>
            <td>Total debt:</td>
            <td>0.00</td>
         </tr>
         <tr>
            <td>Debt in currency:</td>
            <td>0.00</td>
         </tr>
         <tr>
            <td>Currency debt:</td>
            <td>0.00</td>
         </tr>
         <tr>
            <td>Terms of payment:</td>
            <td>0.00</td>
         </tr>
      </table>

    <div class="financial-info">Financial data is of an informative nature. For details and possible ambiguities, please contact our accounting.</div>

      <div class="row filter-contaner">
         <div class="col-md-7">
            <p class="toolbar-amount">
               <span class="toolbar-number">
               Items 1 to 10 of 13 total                        </span>
            </p>
         </div>
         <div class="col-md-3 tab-head">
            <div class="input-box"> <input type="text" class="form-control" id="searchInput"> <i class="fa fa-search"></i> </div>
         </div>
         <div class="col-xs-3 tab-foot">
            <div class="limiter">
               <strong class="limiter-label">Show</strong>
               <select id="limiter" class="limiter-options">
                  <option value="http://m2.wc.b2b.com/sales/order/history/?limit=10" selected="selected">
                     10                    
                  </option>
                  <option value="http://m2.wc.b2b.com/sales/order/history/?limit=20">
                     20                    
                  </option>
                  <option value="http://m2.wc.b2b.com/sales/order/history/?limit=50">
                     50                    
                  </option>
               </select>
               <span class="limiter-text">per page</span>
            </div>
         </div>
      </div>
   <div id="elements">
         <ol class="collection collection-container" id="filter">
            <li class="item item-container" >
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Rb.')) ?>"><?= $block->escapeHtml(__('Rb.')) ?></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('PJ')) ?>"><?= $block->escapeHtml(__('PJ')) ?></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Description')) ?>"><?= $block->escapeHtml(__('Description')) ?></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Number')) ?>"><?= $block->escapeHtml(__('Number')) ?></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Due date')) ?>"><?= $block->escapeHtml(__('Due date')) ?></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance(LVT)')) ?>"><?= $block->escapeHtml(__('Balance(LVT)')) ?></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance due')) ?>"><?= $block->escapeHtml(__('Balance due')) ?></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Remaining balance')) ?>"><?= $block->escapeHtml(__('Remaining balance')) ?></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Days of delay')) ?>"><?= $block->escapeHtml(__('Days of delay')) ?></div>
               <div class="attribute" ></div>
            </li>
            <li class="item item-container" data-role="collapsible">
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Rb.')) ?>">1.</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('PJ')) ?>">1</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Description')) ?>"></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Number')) ?>">FO1593-00004</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Due date')) ?>">03/30/2015</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance(LVT)')) ?>"><span>492,63</span></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance due')) ?>">492,63</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Remaining balance')) ?>">0.00</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Days of delay')) ?>">0</div>
               <div class="attribute" ><span class="excel-icon"><div class="get-invoice">Get invoice</div> </span></div>
            </li>
            <li class="item item-container" data-role="collapsible">
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Rb.')) ?>">2.</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('PJ')) ?>">1</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Description')) ?>"></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Number')) ?>">FO1593-00004</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Due date')) ?>">02/30/2018</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance(LVT)')) ?>"><span>492,63</span></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance due')) ?>">492,63</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Remaining balance')) ?>">0.00</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Days of delay')) ?>">0</div>
               <div class="attribute" ><span class="excel-icon"><div class="get-invoice">Get invoice</div> </span></div>
            </li>
            <li class="item item-container" data-role="collapsible">
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Rb.')) ?>">3.</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('PJ')) ?>">1</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Description')) ?>"></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Number')) ?>">FO1593-00006</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Due date')) ?>">03/30/2015</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance(LVT)')) ?>"><span>492,63</span></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance due')) ?>">492,63</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Remaining balance')) ?>">0.00</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Days of delay')) ?>">0</div>
               <div class="attribute" ><span class="excel-icon"><div class="get-invoice">Get invoice</div> </span></div>
            </li>
            <li class="item item-container" data-role="collapsible">
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Rb.')) ?>">4.</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('PJ')) ?>">1</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Description')) ?>"></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Number')) ?>">FO1111-00004</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Due date')) ?>">03/30/2015</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance(LVT)')) ?>"><span>492,63</span></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance due')) ?>">562,63</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Remaining balance')) ?>">0.00</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Days of delay')) ?>">0</div>
               <div class="attribute" ><span class="excel-icon"><div class="get-invoice">Get invoice</div> </span></div>
            </li>
            <li class="item item-container" data-role="collapsible">
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Rb.')) ?>">5.</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('PJ')) ?>">1</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Description')) ?>"></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Number')) ?>">F11593-00004</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Due date')) ?>">03/30/2015</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance(LVT)')) ?>"><span>492,63</span></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance due')) ?>">492,63</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Remaining balance')) ?>">0.00</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Days of delay')) ?>">0</div>
               <div class="attribute" ><span class="excel-icon"><div class="get-invoice">Get invoice</div> </span></div>
            </li>
            <li class="item item-container" data-role="collapsible">
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Rb.')) ?>">6.</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('PJ')) ?>">1</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Description')) ?>"></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Number')) ?>">FO1593-0120</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Due date')) ?>">03/30/2015</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance(LVT)')) ?>"><span>492,63</span></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance due')) ?>">999,63</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Remaining balance')) ?>">0.00</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Days of delay')) ?>">0</div>
               <div class="attribute" ><span class="excel-icon"><div class="get-invoice">Get invoice</div> </span></div>
            </li>
            <li class="item item-container" data-role="collapsible">
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Rb.')) ?>">7.</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('PJ')) ?>">1</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Description')) ?>"></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Number')) ?>">FO1593-00004</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Due date')) ?>">01/30/2022</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance(LVT)')) ?>"><span>492,63</span></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance due')) ?>">492,63</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Remaining balance')) ?>">0.00</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Days of delay')) ?>">0</div>
               <div class="attribute" ><span class="excel-icon"><div class="get-invoice">Get invoice</div> </span></div>
            </li>

            <li class="item item-container" data-role="collapsible">
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Rb.')) ?>">8.</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('PJ')) ?>">1</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Description')) ?>"></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Number')) ?>">FO1593-00004</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Due date')) ?>">01/20/2021</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance(LVT)')) ?>"><span>492,63</span></div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Balance due')) ?>">789,63</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Remaining balance')) ?>">0.00</div>
               <div class="attribute" data-name="<?= $block->escapeHtml(__('Days of delay')) ?>">0</div>
               <div class="attribute" ><span class="excel-icon"><div class="get-invoice">Get invoice</div> </span></div>
            </li>
         </ol>
   </div>
   <div class="pager">
      <div class="limiter pull-right">
         <strong class="limiter-label">Show</strong>
         <select id="limiter" class="limiter-options">
            <option value="http://m2.wc.b2b.com/sales/order/history/?limit=10" selected="selected">
               10                    
            </option>
            <option value="http://m2.wc.b2b.com/sales/order/history/?limit=20">
               20                    
            </option>
            <option value="http://m2.wc.b2b.com/sales/order/history/?limit=50">
               50                    
            </option>
         </select>
         <span class="limiter-text">per page</span>
      </div>
   </div>
</div>  

<script>
   require(['jquery', 'jquery/ui'], function($){ 
       $('#searchInput').keyup(function(){
      var searchText = $(this).val();
    
      $('ol > li').each(function(){
          var currentLiText = $(this).text(),
              showCurrentLi = currentLiText.indexOf(searchText) !== -1;        
              $(this).toggle(showCurrentLi);
          
      });     
   });
   });
</script>