<div class="order-no">
   <div class="row filter-contaner">
      <div class="col-md-7">
         <div class="sales-title"> 
            <?php echo __("Br.  order 34"); ?> 
         </div>
      </div>
      <div class="col-md-3 tab-head">
         <div class="input-box"> <input type="text" class="form-control" id="searchInput"> <i class="fa fa-search"></i> </div>
      </div>
      <div class="col-xs-3 tab-foot">
         <div class="limiter">
            <strong class="limiter-label">Show</strong>
            <select id="limiter" class="limiter-options">
               <option value="#" selected="selected">
                  10                    
               </option>
               <option value="#">
                  20                    
               </option>
               <option value="#">
                  50                    
               </option>
            </select>
            <span class="limiter-text">per page</span>
         </div>
      </div>
   </div>
   <div id="elements">
      <ol class="collection collection-container" id="filter">
         <li class="item item-container" >
            <div class="attribute" data-name="<?= $block->escapeHtml(__('line')) ?>"><?= $block->escapeHtml(__('line')) ?><span class="group-arrow"></span></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product code')) ?>"><?= $block->escapeHtml(__('Product code')) ?><span class="group-arrow"></span></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product name')) ?>"><?= $block->escapeHtml(__('Product name')) ?><span class="group-arrow"></span></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Packaging')) ?>"><?= $block->escapeHtml(__('Packaging')) ?><span class="group-arrow"></span></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Amount')) ?>"><?= $block->escapeHtml(__('Amount')) ?><span class="group-arrow"></span></div>
            <div class="attribute without-tax" data-name="<?= $block->escapeHtml(__('Amount without tax')) ?>"><?= $block->escapeHtml(__('Amount without tax')) ?><span class="group-arrow"></span></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Status')) ?>"><?= $block->escapeHtml(__('Status')) ?><span class="group-arrow"></span></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Comment')) ?>"><?= $block->escapeHtml(__('Comment')) ?><span class="group-arrow"></span></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Action')) ?>"><?= $block->escapeHtml(__('Action')) ?></div>
         </li>
         <li class="item item-container" data-role="collapsible">
            <div class="attribute" data-name="<?= $block->escapeHtml(__('line')) ?>"></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product code')) ?>">TTKA10340</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product name')) ?>"> REINFORCEMENT PLIERS WORM 280 mm HANDLE </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Packaging')) ?>">1</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Amount')) ?>"> 
            <span class="qty-contaner">
                  <div class="control-qty-cart">
                     <span class=" icon-interface-minus quantity-controls quantity-minus"></span>
                     <input type="number" name="qty" id="qty" maxlength="12" value="1" title="Kol" class="qty-default input-text qty" data-validate="null">
                     <span class="quantity-controls quantity-plus icon-interface-plus"></span>
                  </div>
                  <span class="red-box"></span>
               </span> </div>
            <div class="attribute availability" data-name="<?= $block->escapeHtml(__('Amount without tax')) ?>">
            <span>
                  <div class="tooltip">
                     <span class="vpc">380.00</span> <span class="toolkit-icon"></span>
                     <span class="tooltiptext tooltip-bottom">
                        <p>Price   <span>32.00</span></p>
                        <p>25% VAT <span>400.00</span></p>
                        <p>Total HRK with vat <span>400.00</span></p>
                     </span>
                  </div>
               </span>
            </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Status')) ?>">She’s ready to order </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Comment')) ?>">comments </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Action')) ?>" ><span class="delete-icon"></span></div>            
         </li>
         <li class="item item-container" data-role="collapsible">
            <div class="attribute" data-name="<?= $block->escapeHtml(__('line')) ?>"></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product code')) ?>">TTKA103230</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product name')) ?>"> REINFORCEMENT PLIERS WORM 280 mm HANDLE </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Packaging')) ?>">1</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Amount')) ?>"> 
            <span class="qty-contaner">
                  <div class="control-qty-cart">
                     <span class=" icon-interface-minus quantity-controls quantity-minus"></span>
                     <input type="number" name="qty" id="qty" maxlength="12" value="1" title="Kol" class="qty-default input-text qty" data-validate="null">
                     <span class="quantity-controls quantity-plus icon-interface-plus"></span>
                  </div>
                  <span class="green-box"></span>
               </span> </div>
            <div class="attribute availability" data-name="<?= $block->escapeHtml(__('Amount without tax')) ?>">
            <span>
                  <div class="tooltip">
                     <span class="vpc">380.00</span> <span class="toolkit-icon"></span>
                     <span class="tooltiptext tooltip-bottom">
                        <p>Price   <span>32.00</span></p>
                        <p>25% VAT <span>400.00</span></p>
                        <p>Total HRK with vat <span>400.00</span></p>
                     </span>
                  </div>
               </span>
            </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Status')) ?>">She’s not rady </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Comment')) ?>">comments </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Action')) ?>" ><span class="delete-icon"></span></div>            
         </li>
         <li class="item item-container" data-role="collapsible">
            <div class="attribute" data-name="<?= $block->escapeHtml(__('line')) ?>"></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product code')) ?>">TTKA23413</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product name')) ?>"> REINFORCEMENT PLIERS WORM 280 mm HANDLE </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Packaging')) ?>">1</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Amount')) ?>"> 
            <span class="qty-contaner">
                  <div class="control-qty-cart">
                     <span class=" icon-interface-minus quantity-controls quantity-minus"></span>
                     <input type="number" name="qty" id="qty" maxlength="12" value="1" title="Kol" class="qty-default input-text qty" data-validate="null">
                     <span class="quantity-controls quantity-plus icon-interface-plus"></span>
                  </div>
                  <span class="blue-box"></span>
               </span> </div>
            <div class="attribute availability" data-name="<?= $block->escapeHtml(__('Amount without tax')) ?>">
            <span>
                  <div class="tooltip">
                     <span class="vpc">380.00</span> <span class="toolkit-icon"></span>
                     <span class="tooltiptext tooltip-bottom">
                        <p>Price   <span>32.00</span></p>
                        <p>25% VAT <span>400.00</span></p>
                        <p>Total HRK with vat <span>400.00</span></p>
                     </span>
                  </div>
               </span>
            </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Status')) ?>">She’s not rady </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Comment')) ?>">comments </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Action')) ?>" ><span class="delete-icon"></span></div>            
         </li>
         <li class="item item-container" data-role="collapsible">
            <div class="attribute" data-name="<?= $block->escapeHtml(__('line')) ?>"></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product code')) ?>">TTKA11111</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product name')) ?>"> REINFORCEMENT PLIERS WORM 280 mm HANDLE </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Packaging')) ?>">1</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Amount')) ?>"> 
            <span class="qty-contaner">
                  <div class="control-qty-cart">
                     <span class=" icon-interface-minus quantity-controls quantity-minus"></span>
                     <input type="number" name="qty" id="qty" maxlength="12" value="1" title="Kol" class="qty-default input-text qty" data-validate="null">
                     <span class="quantity-controls quantity-plus icon-interface-plus"></span>
                  </div>
                  <span class="red-box"></span>
               </span> </div>
            <div class="attribute availability" data-name="<?= $block->escapeHtml(__('Amount without tax')) ?>">
            <span>
                  <div class="tooltip">
                     <span class="vpc">380.00</span> <span class="toolkit-icon"></span>
                     <span class="tooltiptext tooltip-bottom">
                        <p>Price   <span>32.00</span></p>
                        <p>25% VAT <span>400.00</span></p>
                        <p>Total HRK with vat <span>400.00</span></p>
                     </span>
                  </div>
               </span>
            </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Status')) ?>">She’s not rady </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Comment')) ?>">comments </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Action')) ?>" ><span class="delete-icon"></span></div>            
         </li>
         <li class="item item-container" data-role="collapsible">
            <div class="attribute" data-name="<?= $block->escapeHtml(__('line')) ?>"></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product code')) ?>">TTKA12345</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product name')) ?>"> REINFORCEMENT PLIERS WORM 280 mm HANDLE </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Packaging')) ?>">1</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Amount')) ?>"> 
            <span class="qty-contaner">
                  <div class="control-qty-cart">
                     <span class=" icon-interface-minus quantity-controls quantity-minus"></span>
                     <input type="number" name="qty" id="qty" maxlength="12" value="1" title="Kol" class="qty-default input-text qty" data-validate="null">
                     <span class="quantity-controls quantity-plus icon-interface-plus"></span>
                  </div>
                  <span class="green-box"></span>
               </span> </div>
            <div class="attribute availability" data-name="<?= $block->escapeHtml(__('Amount without tax')) ?>">
            <span>
                  <div class="tooltip">
                     <span class="vpc">380.00</span> <span class="toolkit-icon"></span>
                     <span class="tooltiptext tooltip-bottom">
                        <p>Price   <span>32.00</span></p>
                        <p>25% VAT <span>400.00</span></p>
                        <p>Total HRK with vat <span>400.00</span></p>
                     </span>
                  </div>
               </span>
            </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Status')) ?>">She’s not rady </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Comment')) ?>">comments </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Action')) ?>" ><span class="delete-icon"></span></div>            
         </li>
         <li class="item item-container" data-role="collapsible">
            <div class="attribute" data-name="<?= $block->escapeHtml(__('line')) ?>"></div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product code')) ?>">TTKA12345</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Product name')) ?>"> REINFORCEMENT PLIERS WORM 280 mm HANDLE </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Packaging')) ?>">1</div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Amount')) ?>"> 
            <span class="qty-contaner">
                  <div class="control-qty-cart">
                     <span class=" icon-interface-minus quantity-controls quantity-minus"></span>
                     <input type="number" name="qty" id="qty" maxlength="12" value="1" title="Kol" class="qty-default input-text qty" data-validate="null">
                     <span class="quantity-controls quantity-plus icon-interface-plus"></span>
                  </div>
                  <span class="blue-box"></span>
               </span> </div>
            <div class="attribute availability" data-name="<?= $block->escapeHtml(__('Amount without tax')) ?>">
            <span>
                  <div class="tooltip">
                     <span class="vpc">380.00</span> <span class="toolkit-icon"></span>
                     <span class="tooltiptext tooltip-bottom">
                        <p>Price   <span>32.00</span></p>
                        <p>25% VAT <span>400.00</span></p>
                        <p>Total HRK with vat <span>400.00</span></p>
                     </span>
                  </div>
               </span>
            </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Status')) ?>">She’s not rady </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Comment')) ?>">comments </div>
            <div class="attribute" data-name="<?= $block->escapeHtml(__('Action')) ?>" ><span class="delete-icon"></span></div>            
         </li>
      </ol>
   </div>
   <div class="pager">
      <div class="limiter pull-right">
         <strong class="limiter-label">Show</strong>
         <select id="limiter" class="limiter-options">
            <option value="#" selected="selected">
               10                    
            </option>
            <option value="#">
               20                    
            </option>
            <option value="#">
               50                    
            </option>
         </select>
         <span class="limiter-text">per page</span>
      </div>
   </div>
</div>
<script>
   require(['jquery', 'jquery/ui'], function($){ 
       $('#searchInput').keyup(function(){
      var searchText = $(this).val();    
      $('ol > li').each(function(){
          var currentLiText = $(this).text(),
              showCurrentLi = currentLiText.indexOf(searchText) !== -1;        
              $(this).toggle(showCurrentLi);          
      });     
   });
   });
</script>
<script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            $('.quantity-plus').click(function () {
                var currentQTY = parseInt($(this).parent().parent().find(".qty-default").val());
                currentQTY = currentQTY + 1;
                $(this).parent().parent().find(".qty-default").val(currentQTY);
            });

            $('.quantity-minus').click(function () {
                var currentQTY = parseInt($(this).parent().parent().find(".qty-default").val());
                currentQTY = currentQTY - 1;
                if (currentQTY > 0) {
                    $(this).parent().parent().find(".qty-default").val(currentQTY);
                }
            });            
        });
    </script>