<section class="container-inner registration-bg">
    <div class="row">
        <div class="col-md-5 textcenter"><img src="<?php echo $block->getViewFileUrl('Wcb_Registrationblock::images/registration-banner.png');?>" /></div>
        <div class="col-md-5 textCenterInMobile"><h2>Not registered yet, <span>Register now</span></h2>
            <p>and access more than 125000 products</p>
            <a href="https://eshop.wuerth.com.hr/A/hr-HR/Account/RegisterHome" class="primary-button">Registriraj se</a>

        </div>
    </div>
</section>