<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\RequisitionList\Block\Requisition\View\Details */
/** @var $escaper \Magento\Framework\Escaper */
?>

<div class="actions-toolbar requisition-view-buttons" data-mage-init='{"requisitionActions":{ }}'>
    <div class="primary">
        <?php if ($block->getItemCount()): ?>
        <!-- ko scope: 'requisition.list.items.massaction.addtocart' -->
        <button type="button"
                title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                class="action primary disabled"
                data-bind="
                    css: {
                        disabled: !isEnable()
                    },
                    click: applyAction.bind($data, {
                        requisition_id: '<?= (int)$block->getRequest()->getParam('requisition_id') ?>'
                    })"
                data-mobile-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>">
            <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
        </button>
        <!-- /ko -->
        <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "requisition.list.items.massaction.addtocart": {
                                "component": "Magento_RequisitionList/js/requisition/items/grid/massaction/add-to-cart",
                                "selectProvider": "requisition.item.grid.selection.provider",
                                "hasConfirm": true,
                                "action": "<?= $escaper->escapeUrl($block->getUrl(
                                    'requisition_list/item/addToCart'
                                )) ?>"
                            }
                        }
                    }
                }
            }
        </script>
        <button type="button"
                title="<?= $escaper->escapeHtmlAttr(__('Update List')) ?>"
                class="action secondary"
                data-action="update-list"
                data-mobile-label="<?= $escaper->escapeHtmlAttr(__('Update List')) ?>"
                data-update-list='{
                "updateUrl":"<?= $escaper->escapeUrl($block->getUrl('*/item/update', [
                    'requisition_id' => (int)$block->getRequest()->getParam('requisition_id')
                ])) ?>"
                }'>
            <span><?= $escaper->escapeHtml(__('Update List')) ?></span>
        </button>
        <?php endif ?>
        <button type="button"
                title="<?= $escaper->escapeHtmlAttr(__('Delete Requisition List')) ?>"
                class="action secondary delete"
                data-action="remove-list"
                data-mobile-label="<?= $escaper->escapeHtmlAttr(__('Delete Requisition List')) ?>"
                data-delete-list='{
                "deleteUrl":"<?= $escaper->escapeUrl($block->getUrl('*/requisition/delete', [
                    'requisition_id' => (int)$block->getRequest()->getParam('requisition_id')
                ])) ?>",
                "listName": "<?= $escaper->escapeHtml($block->getRequisitionList()->getName()) ?>"
                }'>
            <span><?= $escaper->escapeHtml(__('Delete Requisition List')) ?></span>
        </button>
    </div>
</div>
