<?php
   $confirmationLink = $block->getConfirmationLink();
   ?>
<div class="register-success">
   <span class="success-image">
   <img src=" <?php echo $block->getViewFileUrl('Wcb_CustomerRegistration::images/success-image-group.svg'); ?>" />
   </sapn>
   <h2><?= __("You must confirm your account."); ?></h2>
   <p> <?= __(sprintf("Please check your email for the confirmation link or <a href='%s'><span> click here </span> </a> for a new link.",
      $confirmationLink
      )); ?>
   </p>
</div>